#!/bin/ash
unset IFS
set -euo pipefail

usage() {
    printf "Usage: %s <OPTIONS>\n" "$0"
    printf "\n"
    printf -- "--name <name>\t\t\tPackage name (Required, nonblank).\n"
    printf -- "--version <version>\t\tPackage version (Required, nonblank).\n"
    printf -- "--release <release>\t\tPackage release version (Required, nonblank).\n"
    printf -- "--arch <architecture>\t\tPackage architecture (Required, nonblank).\n"
    printf -- "--maintainer <maintainer>\tPackage maintainer of the form \"<name> <email>\" (Required, RFC822 format).\n"
    printf -- "--summary <summary>\t\tPackage summary (Required, nonblank, ignored).\n"
    printf -- "--description <description>\tPackage description (Required, nonblank).\n"
    printf -- "--license <license>\t\tPackage license (Required, nonblank).\n"
    printf -- "--dependencies <dependencies>\tPrerequisite package constraints (Optional).\n"
    printf -- "--changelog-file <path>\tChangelog location (Required, nonblank, ignored).\n"
    printf -- "--url <homepage>\t\tPackage homepage (Required, nonblank).\n"
    printf -- "--help\t\t\t\tShow usage menu.\n"
}

ARTIFACT_DIR='.rockhopper/alpine'

clean() {
    rm -rf "$INTERNAL_DIR"
}

while [ "$#" -ge 1 ]; do
    case "$1" in
    '--help')
        usage
        exit
        ;;
    '--name')
        shift
        export NAME="$1"
        shift
        ;;
    '--version')
        shift
        export VERSION="$1"
        shift
        ;;
    '--release')
        shift
        export RELEASE="$1"
        shift
        ;;
    '--arch')
        shift
        export ARCH="$1"
        shift
        ;;
    '--maintainer')
        shift
        export MAINTAINER="$1"
        shift
        ;;
    '--summary')
        shift
        export SUMMARY="$1"
        shift
        ;;
    '--description')
        shift
        export DESCRIPTION="$1"
        shift
        ;;
    '--license')
        shift
        export LICENSE="$1"
        shift
        ;;
    '--dependencies')
        shift
        export DEPENDENCIES="$1"
        shift
        ;;
    '--changelog-file')
        shift
        export CHANGELOG_PATH="$1"
        shift
        ;;
    '--url')
        shift
        export URL="$1"
        shift
        ;;
    *)
        usage
        exit 1
        ;;
    esac
done

if [ "${NAME:-}" = '' ]; then
    echo "error: blank/missing --name <name>"
    usage
    exit 1
fi

if [ "${VERSION:-}" = '' ]; then
    echo "error: blank/missing --version <version>"
    usage
    exit 1
fi

if [ "${RELEASE:-}" = '' ]; then
    echo "error: blank/missing --release <release>"
    usage
    exit 1
fi

if [ "${ARCH:-}" = '' ]; then
    echo "error: blank/missing --arch <architecture>"
    usage
    exit 1
fi

if [ "${MAINTAINER:-}" = '' ]; then
    echo "error: blank/missing --maintainer <maintainer>"
    usage
    exit 1
fi

if [ "${SUMMARY:-}" = '' ]; then
    echo "error: blank/missing --summary <summary>"
    usage
    exit 1
fi

if [ "${DESCRIPTION:-}" = '' ]; then
    echo "error: blank/missing --description <description>"
    usage
    exit 1
fi

if [ "${LICENSE:-}" = '' ]; then
    echo "error: blank/missing --license <license>"
    usage
    exit 1
fi

if [ "${CHANGELOG_PATH:-}" = '' ]; then
    echo "error: blank/missing --changelog-file <path>"
    usage
    exit 1
fi

if [ "${URL:-}" = '' ]; then
    echo "error: blank/missing --url <homepage>"
    usage
    exit 1
fi

cd /src

INTERNAL_DIR="$NAME"

clean
mkdir -p "$INTERNAL_DIR"

APKBUILD="# Maintainer: $MAINTAINER
pkgname=$NAME
pkgver=$VERSION
pkgrel=$RELEASE
pkgdesc=\"$DESCRIPTION\"
url=\"$URL\"
arch=\"$ARCH\"
license=\"$LICENSE\"
depends=\"${DEPENDENCIES:-}\"
makedepends=\"\"
checkdepends=\"\"
install=\"\"
subpackages=\"\"
source=\"\"
builddir=\"\$srcdir/\"
options=\"!check\"

prepare() {
    default_prepare
    cp -r /src/data/* \"\$builddir\"
}

package() {"

cd data
for f in $(find . -print); do
    f="${f#./}"

    if [ "$f" = '.' ]; then
        continue
    fi

    if [ -d "$f" ]; then
        APKBUILD="$APKBUILD\n\tmkdir -p \"\$pkgdir/$f\""
    elif [ -f "$f" ]; then
        APKBUILD="$APKBUILD\n\tcp \"\$srcdir/$f\" \"\$pkgdir/$f\""
    else
        echo "error: unsupported file system file type for path: data/$f"
        exit 1
    fi
done
cd ..

APKBUILD="$APKBUILD\n}"

printf "$APKBUILD\n" >"$INTERNAL_DIR/APKBUILD"

SRC_DIR="$INTERNAL_DIR/src"
mkdir -p "$SRC_DIR"

cd "$INTERNAL_DIR"
abuild -F checksum
abuild -F -r
cd /src

mkdir -p "$ARTIFACT_DIR"
cp "/root/packages/src/$(uname -m)/$NAME-$VERSION-r$RELEASE.apk" "$ARTIFACT_DIR"

clean
