#!/bin/bash
unset IFS
set -euo pipefail

#
# Windows ISA identifiers
#
# https://learn.microsoft.com/en-us/cpp/build/projects-and-build-systems-cpp?view=msvc-170
# https://manpages.debian.org/trixie/wixl/wixl.1.en.html
#
# Warning:
#
# wixl uses UPPERCASE notation for ISA's.
#
# ISA independent package convention: "0"
#
ROCKHOPPER_ARCH="${ROCKHOPPER_ARCH:-}"

#
# Windows GUID / UUIDv4
#
# https://learn.microsoft.com/en-us/windows/win32/api/guiddef/ns-guiddef-guid
# https://www.rfc-editor.org/rfc/rfc9562#name-uuid-version-4
#
# Warning:
#
# Reuse ROCKHOPPER_UPGRADE_CODE across different versions of the same package,
# as the Windows Install service uses ROCKHOPPER_UPGRADE_CODE to manage software updates.
#
# However, generate a fresh ROCKHOPPER_PRODUCT_CODE for different packages,
# as well as for different versions of the same package.
#
ROCKHOPPER_UPGRADE_CODE="${ROCKHOPPER_UPGRADE_CODE:-}"
ROCKHOPPER_PRODUCT_CODE="${ROCKHOPPER_PRODUCT_CODE:-}"

#
# Microsoft locale ID
# https://learn.microsoft.com/en-us/openspecs/office_standards/ms-oe376/6c085406-a698-4e12-9d4d-c3b0ee3dbc4a
#
# en-US: "1033"
#
ROCKHOPPER_LCID="${ROCKHOPPER_LCID:-}"

# #
# # Microsft Code Page
# # https://learn.microsoft.com/en-us/windows/win32/intl/code-page-identifiers
# #
# # UTF-8: 65001
# #
# ROCKHOPPER_CODE_PAGE="${ROCKHOPPER_CODE_PAGE:-65001}"

ROCKHOPPER_LOG_LEVEL="${ROCKHOPPER_LOG_LEVEL:-info}"
ROCKHOPPER_IMAGE="${ROCKHOPPER_IMAGE:-unknown image}"
ROCKHOPPER_NAME="${ROCKHOPPER_NAME:-}"
ROCKHOPPER_VERSION="${ROCKHOPPER_VERSION:-}"
ROCKHOPPER_MANUFACTURER="${ROCKHOPPER_MANUFACTURER:-}"
ROCKHOPPER_SUMMARY="${ROCKHOPPER_SUMMARY:-}"
ROCKHOPPER_COPYRIGHT="${ROCKHOPPER_COPYRIGHT:-}"
ROCKHOPPER_LICENSE="${ROCKHOPPER_LICENSE:-}"
ROCKHOPPER_MOUNT="${ROCKHOPPER_MOUNT:-/mnt/rockhopper}"

# Requires unique basenames for each file path
ROCKHOPPER_DATA="${ROCKHOPPER_DATA:-"$ROCKHOPPER_MOUNT/rockhopper-data"}"

ROCKHOPPER_SPECS="${ROCKHOPPER_SPECS:-"$HOME/rockhopper-specs"}"
ROCKHOPPER_ARTIFACT="${ROCKHOPPER_ARTIFACT:-"$ROCKHOPPER_MOUNT/.rockhopper/windows"}"
ROCKHOPPER_MSI_BUILD="${ROCKHOPPER_MSI_BUILD:-/tmp/windows}"

# Forward rockhopper environment variables to Jinja
for K in $(compgen -v | grep '^ROCKHOPPER_'); do
    export "$K"
done

usage() {
    printf "Usage: %s [<OPTION>]\n" "$0"
    printf "\n"
    printf -- "--debug -d\tIncrease logging\n"
    printf -- "--quiet -q\tReduce logging\n"
    printf -- "--help -h\tShow usage menu\n"
    printf -- "--version -V\tShow version banner\n"
}

banner() {
    echo "$0 0.0.9"
}

while [ "$#" -ge 1 ]; do
    case "$1" in
    '--debug' | '-d')
        shift
        ROCKHOPPER_LOG_LEVEL='debug'
        ;;
    '--quiet' | 'q')
        shift
        ROCKHOPPER_LOG_LEVEL='quiet'
        ;;
    '--help' | '-h')
        usage
        exit
        ;;
    '--version' | '-V')
        banner
        exit
        ;;
    *)
        usage
        exit 1
        ;;
    esac
done

if [ "$ROCKHOPPER_LOG_LEVEL" = 'debug' ]; then
    env | grep '^ROCKHOPPER_' | sort
    set -x
fi

validate() {
    REQUIRED_ENV_VARS=(
        ROCKHOPPER_ARCH
        ROCKHOPPER_UPGRADE_CODE
        ROCKHOPPER_PRODUCT_CODE
        ROCKHOPPER_LCID
        # ROCKHOPPER_CODE_PAGE
        ROCKHOPPER_NAME
        ROCKHOPPER_VERSION
        ROCKHOPPER_MANUFACTURER
        ROCKHOPPER_SUMMARY
        ROCKHOPPER_LICENSE
        ROCKHOPPER_MOUNT
        ROCKHOPPER_DATA
        ROCKHOPPER_SPECS
        ROCKHOPPER_ARTIFACT
        ROCKHOPPER_MSI_BUILD
    )

    for REQUIRED_ENV_VAR in "${REQUIRED_ENV_VARS[@]}"; do
        eval "REQUIRED_ENV_VAL=\$$REQUIRED_ENV_VAR"

        if [ -z "$REQUIRED_ENV_VAL" ]; then
            echo "error: ${ROCKHOPPER_IMAGE} blank/missing env var: ${REQUIRED_ENV_VAR}"
            exit 1
        fi
    done
}

clean() {
    rm -rf "$ROCKHOPPER_MSI_BUILD"
}

validate
clean

LIC=''

if [ -n "$ROCKHOPPER_COPYRIGHT" ]; then
    LIC="Copyright: $ROCKHOPPER_COPYRIGHT"
fi

LIC="${LIC}\nLicense: $ROCKHOPPER_LICENSE"
mkdir -p "$ROCKHOPPER_MSI_BUILD"
printf "$LIC\n" >"$ROCKHOPPER_MSI_BUILD/LICENSE.txt"

for f in $(find "$ROCKHOPPER_DATA" -type f -print); do
    cp "$f" "$ROCKHOPPER_MSI_BUILD"
done

cd "$ROCKHOPPER_MSI_BUILD"

export MSI_COMPONENTS="$(wix-tree .)"

cd "$ROCKHOPPER_MOUNT"

PRODUCT="$ROCKHOPPER_MSI_BUILD/product.wxs"
rsubst "$ROCKHOPPER_SPECS/product.wxs.j2" >"$PRODUCT"

if [ "$ROCKHOPPER_LOG_LEVEL" = 'debug' ]; then
    echo "product:"
    cat "$PRODUCT"
fi

mkdir -p "$ROCKHOPPER_ARTIFACT"
ARTIFACT="$ROCKHOPPER_ARTIFACT/${ROCKHOPPER_NAME}_${ROCKHOPPER_VERSION}"
WIXL_ARCH=''

if [ "$ROCKHOPPER_ARCH" = '0' ]; then
    ARTIFACT="$ARTIFACT.msi"
else
    ARTIFACT="${ARTIFACT}_${ROCKHOPPER_ARCH}.msi"
    WIXL_ARCH="-a ${ROCKHOPPER_ARCH}"
fi

# dpkg-deb() {
#     if [ "$ROCKHOPPER_LOG_LEVEL" = 'quiet' ]; then
#         command dpkg-deb "$@" >/dev/null
#     else
#         command dpkg-deb "$@"
#     fi
# }

wixl $WIXL_ARCH -o "$ARTIFACT" "$PRODUCT"

clean
