#!/bin/bash
unset IFS
set -euo pipefail

rocklet_log_level="${rocklet_log_level:-info}"
rocklet_image="${rocklet_image:-unknown image}"
rocklet_mount_path="${rocklet_mount_path:-/mnt/rockhopper}"
rocklet_name="${rocklet_name:-}"
rocklet_version="${rocklet_version:-}"
rocklet_rev="${rocklet_rev:-}"
rocklet_copyright="${rocklet_copyright:-}"
rocklet_license="${rocklet_license:-}"
rocklet_templates="${rocklet_templates:-"$HOME/templates"}"
rocklet_cache="${rocklet_cache:-"$rocklet_mount_path/.rockhopper"}"
rocklet_artifact="${rocklet_artifact:-"$rocklet_cache/artifacts/ubuntu"}"
rocklet_apt_build="${rocklet_apt_build:-/tmp/ubuntu}"
rocklet_os_arch="${rocklet_os_arch:-"$(dpkg-architecture -qDEB_HOST_ARCH)"}"
rocklet_priority="${rocklet_priority:-optional}"
rocklet_dependencies="${rocklet_dependencies:-}"

# Forward rockhopper environment variables to Jinja
for K in $(compgen -v | grep '^rocklet_'); do
    export "$K"
done

usage() {
    printf "Usage: %s [<OPTION>]\n" "$0"
    printf "\n"
    printf -- "--debug -d\tIncrease logging\n"
    printf -- "--quiet -q\tReduce logging\n"
    printf -- "--help -h\tShow usage menu\n"
    printf -- "--version -V\tShow version banner\n"
}

banner() {
    echo "$0 0.0.12"
}

while [ "$#" -ge 1 ]; do
    case "$1" in
    '--debug' | '-d')
        shift
        rocklet_log_level='debug'
        ;;
    '--quiet' | 'q')
        shift
        rocklet_log_level='quiet'
        ;;
    '--help' | '-h')
        usage
        exit
        ;;
    '--version' | '-V')
        banner
        exit
        ;;
    *)
        usage
        exit 1
        ;;
    esac
done

if [ "$rocklet_log_level" = 'debug' ]; then
    env | grep '^rocklet_' | sort
    set -x
fi

validate() {
    required_env_vars=(
        rocklet_apt_build
        rocklet_artifact
        rocklet_cache
        rocklet_image
        rocklet_license
        rocklet_log_level
        rocklet_mount_path
        rocklet_name
        rocklet_os_arch
        rocklet_templates
        rocklet_version
    )

    for required_env_var in "${required_env_vars[@]}"; do
        eval "required_env_val=\$$required_env_var"

        if [ -z "$required_env_val" ]; then
            echo "error: ${rocklet_image} blank/missing env var: ${required_env_var}"
            exit 1
        fi
    done
}

clean() {
    rm -rf "$rocklet_apt_build"
}

validate
clean

mkdir -p "$rocklet_apt_build/DEBIAN"

if [ -n "$rocklet_copyright" ]; then
    COPYRIGHT="$rocklet_apt_build/DEBIAN/copyright"
    rsubst --strict "$rocklet_templates/copyright.j2" >"$COPYRIGHT"

    if [ "$rocklet_log_level" = 'debug' ]; then
        echo "copyright:"
        cat "$COPYRIGHT"
    fi
fi

CONTROL="$rocklet_apt_build/DEBIAN/control"
rsubst --strict "$rocklet_templates/control.j2" >"$CONTROL"

if [ "$rocklet_log_level" = 'debug' ]; then
    echo "control:"
    cat "$CONTROL"
fi

export source_media="$rocklet_cache/source-media"
mkdir -p "$source_media"
cp -r "$source_media/"* "$rocklet_apt_build"
mkdir -p "$rocklet_artifact"
artifact="$rocklet_artifact/${rocklet_name}_${rocklet_version}"

if [ -n "$rocklet_rev" ]; then
    artifact="${artifact}-${rocklet_rev}"
fi

artifact="${artifact}_${rocklet_os_arch}.deb"

dpkg-deb() {
    if [ "$rocklet_log_level" = 'quiet' ]; then
        command dpkg-deb "$@" >/dev/null
    else
        command dpkg-deb "$@"
    fi
}

dpkg-deb --build "$rocklet_apt_build" "$artifact"

clean
