#!/bin/bash
unset IFS
set -euo pipefail

ROCKHOPPER_LOG_LEVEL="${ROCKHOPPER_LOG_LEVEL:-info}"
ROCKHOPPER_IMAGE="${ROCKHOPPER_IMAGE:-unknown image}"
ROCKHOPPER_NAME="${ROCKHOPPER_NAME:-}"
ROCKHOPPER_VERSION="${ROCKHOPPER_VERSION:-}"
ROCKHOPPER_REV="${ROCKHOPPER_REV:-}"
ROCKHOPPER_COPYRIGHT="${ROCKHOPPER_COPYRIGHT:-}"
ROCKHOPPER_LICENSE="${ROCKHOPPER_LICENSE:-}"
ROCKHOPPER_MOUNT="${ROCKHOPPER_MOUNT:-/mnt/rockhopper}"
ROCKHOPPER_DATA="${ROCKHOPPER_DATA:-"$ROCKHOPPER_MOUNT/rockhopper-data"}"
ROCKHOPPER_SPECS="${ROCKHOPPER_SPECS:-"$HOME/rockhopper-specs"}"
ROCKHOPPER_ARTIFACT="${ROCKHOPPER_ARTIFACT:-"$ROCKHOPPER_MOUNT/.rockhopper/ubuntu"}"
ROCKHOPPER_APT_BUILD="${ROCKHOPPER_APT_BUILD:-/tmp/ubuntu}"
ROCKHOPPER_ARCH="${ROCKHOPPER_ARCH:-all}"

# Forward rockhopper environment variables to Jinja
for K in $(compgen -v | grep '^ROCKHOPPER_'); do
    export "$K"
done

usage() {
    printf "Usage: %s [<OPTION>]\n" "$0"
    printf "\n"
    printf -- "--debug -d\tIncrease logging\n"
    printf -- "--quiet -q\tReduce logging\n"
    printf -- "--help -h\tShow usage menu\n"
    printf -- "--version -V\tShow version banner\n"
}

banner() {
    echo "$0 0.0.8"
}

while [ "$#" -ge 1 ]; do
    case "$1" in
    '--debug' | '-d')
        shift
        ROCKHOPPER_LOG_LEVEL='debug'
        ;;
    '--quiet' | 'q')
        shift
        ROCKHOPPER_LOG_LEVEL='quiet'
        ;;
    '--help' | '-h')
        usage
        exit
        ;;
    '--version' | '-V')
        banner
        exit
        ;;
    *)
        usage
        exit 1
        ;;
    esac
done

if [ "$ROCKHOPPER_LOG_LEVEL" = 'debug' ]; then
    env | grep '^ROCKHOPPER_' | sort
    set -x
fi

validate() {
    REQUIRED_ENV_VARS=(
        ROCKHOPPER_NAME
        ROCKHOPPER_VERSION
        ROCKHOPPER_LICENSE
        ROCKHOPPER_MOUNT
        ROCKHOPPER_DATA
        ROCKHOPPER_SPECS
        ROCKHOPPER_ARTIFACT
        ROCKHOPPER_APT_BUILD
        ROCKHOPPER_ARCH
    )

    for REQUIRED_ENV_VAR in "${REQUIRED_ENV_VARS[@]}"; do
        eval "REQUIRED_ENV_VAL=\$$REQUIRED_ENV_VAR"

        if [ -z "$REQUIRED_ENV_VAL" ]; then
            echo "error: ${ROCKHOPPER_IMAGE} blank/missing env var: ${REQUIRED_ENV_VAR}"
            exit 1
        fi
    done
}

clean() {
    rm -rf "$ROCKHOPPER_APT_BUILD"
}

validate
clean

mkdir -p "$ROCKHOPPER_APT_BUILD/DEBIAN"
CONTROL="$ROCKHOPPER_APT_BUILD/DEBIAN/control"
rsubst "$ROCKHOPPER_SPECS/control.j2" >"$CONTROL"

if [ "$ROCKHOPPER_LOG_LEVEL" = 'debug' ]; then
    echo "control:"
    cat "$CONTROL"
fi

LIC='Files: *'

if [ -n "$ROCKHOPPER_COPYRIGHT" ]; then
    LIC="${LIC}\nCopyright: $ROCKHOPPER_COPYRIGHT"
fi

LIC="${LIC}\nLicense: $ROCKHOPPER_LICENSE"
printf "$LIC\n" >"$ROCKHOPPER_APT_BUILD/DEBIAN/copyright"

cp -r "$ROCKHOPPER_DATA/"* "$ROCKHOPPER_APT_BUILD"
mkdir -p "$ROCKHOPPER_ARTIFACT"
ARTIFACT="$ROCKHOPPER_ARTIFACT/${ROCKHOPPER_NAME}_${ROCKHOPPER_VERSION}"

if [ -n "$ROCKHOPPER_REV" ]; then
    ARTIFACT="${ARTIFACT}-${ROCKHOPPER_REV}"
fi

ARTIFACT="${ARTIFACT}_${ROCKHOPPER_ARCH}.deb"

dpkg-deb() {
    if [ "$ROCKHOPPER_LOG_LEVEL" = 'quiet' ]; then
        command dpkg-deb "$@" >/dev/null
    else
        command dpkg-deb "$@"
    fi
}

dpkg-deb --build "$ROCKHOPPER_APT_BUILD" "$ARTIFACT"

clean
