#!/bin/bash
unset IFS
set -euo pipefail

rocklet_log_level="${rocklet_log_level:-info}"
rocklet_image="${rocklet_image:-unknown image}"
rocklet_mount_path="${rocklet_mount_path:-/mnt/rockhopper}"
rocklet_name="${rocklet_name:-}"
rocklet_version="${rocklet_version:-}"
rocklet_rev="${rocklet_rev:-}"
rocklet_maintainer="${rocklet_maintainer:-}"
rocklet_origin="${rocklet_origin:-}"
rocklet_dependencies="${rocklet_dependencies:-}"
rocklet_copyright="${rocklet_copyright:-}"
rocklet_license="${rocklet_license:-}"
rocklet_summary="${rocklet_summary:-}"
rocklet_description="${rocklet_description:-}"
rocklet_templates="${rocklet_templates:-"$HOME/templates"}"
rocklet_cache="${rocklet_cache:-"$rocklet_mount_path/.rockhopper"}"
rocklet_pkg_build="${rocklet_pkg_build:-/tmp/freebsd}"
rocklet_os_arch="${rocklet_os_arch:-"freebsd:*:$(uname -m)"}"

default_artifact="$rocklet_cache/artifacts/freebsd"
freebsd_version="${rocklet_os_arch#*:}"
freebsd_version="${freebsd_version%%:*}"

if [ "$freebsd_version" != '*' ]; then
    default_artifact="$default_artifact-$freebsd_version"
fi

abi="${rocklet_os_arch##*:}"

if [ "$abi" != '*' ]; then
    default_artifact="$default_artifact-$abi"
fi

rocklet_artifact="${rocklet_artifact:-"$default_artifact"}"

# Forward rockhopper environment variables to Jinja
for K in $(compgen -v | grep '^rocklet_'); do
    export "$K"
done

usage() {
    printf "Usage: %s [<OPTION>]\n" "$0"
    printf "\n"
    printf -- "--debug -d\tIncrease logging\n"
    printf -- "--quiet -q\tReduce logging\n"
    printf -- "--help -h\tShow usage menu\n"
    printf -- "--version -V\tShow version banner\n"
}

ROCKHOPPER_VERSION='0.0.17'
ROCKHOPPER_REV='1'

banner() {
    echo "$0 $ROCKHOPPER_VERSION-$ROCKHOPPER_REV"
}

while [ "$#" -ge 1 ]; do
    case "$1" in
    '--debug' | '-d')
        shift
        rocklet_log_level='debug'
        ;;
    '--quiet' | 'q')
        shift
        rocklet_log_level='quiet'
        ;;
    '--help' | '-h')
        usage
        exit
        ;;
    '--version' | '-V')
        banner
        exit
        ;;
    *)
        usage
        exit 1
        ;;
    esac
done

if [ "$rocklet_log_level" = 'debug' ]; then
    env | grep '^rocklet_' | sort
    set -x
fi

validate() {
    required_env_vars=(
        rocklet_artifact
        rocklet_cache
        rocklet_description
        rocklet_image
        rocklet_log_level
        rocklet_maintainer
        rocklet_mount_path
        rocklet_name
        rocklet_origin
        rocklet_os_arch
        rocklet_pkg_build
        rocklet_summary
        rocklet_templates
        rocklet_version
    )

    for required_env_var in "${required_env_vars[@]}"; do
        eval "required_env_val=\$$required_env_var"

        if [ -z "$required_env_val" ]; then
            echo "error: ${rocklet_image} blank/missing env var: ${required_env_var}" >&2
            exit 1
        fi
    done
}

clean() {
    rm -rf "$rocklet_pkg_build"
}

validate
clean

source_media="$rocklet_cache/source-media"
mkdir -p "$source_media"

mkdir -p "$rocklet_pkg_build"
cp -r "$source_media"/* "$rocklet_pkg_build"

IFS=',' read -r -a lics <<<"$rocklet_license"
licenses=''

for i in "${!lics[@]}"; do
    license="\"${lics[$i]}\""
    licenses="${licenses}${license},"
done

export licenses

is_no_arch='0'

if [ "$abi" = '*' ]; then
    is_no_arch='1'
fi

export is_no_arch
export metrics_b="$(du -sb "$source_media" | awk '{ print $1 }')"

directories=''
checksums=''

cd "$source_media"

for f in $(find .); do
    f="${f#./}"

    if [ "$f" = '.' ]; then
        continue
    fi

    if [ -d "$f" ]; then
        directories="${directories}\"/$f\": y,"
    elif [ -f "$f" ]; then
        checksum="$(sha256sum "$f" | awk '{ print $1 }')"
        checksums="${checksums}\"/${f}\": \"$checksum\","
    else
        echo "error: ${rocklet_image}: unsupported file system file type for path: ${source_media}/${f}" >&2
        exit 1
    fi
done

export directories
export checksums
MANIFEST="$rocklet_pkg_build/+MANIFEST"
rsubst --strict "$rocklet_templates/+MANIFEST.j2" >"$MANIFEST"

if [ "$rocklet_log_level" = 'debug' ]; then
    echo '+MANIFEST':
    cat "$MANIFEST"
fi

artifact="$rocklet_artifact/${rocklet_name}-${rocklet_version}"

if [ -n "$rocklet_rev" ]; then
    artifact="${artifact}_${rocklet_rev}"
fi

artifact="$artifact.pkg"

cd "$rocklet_pkg_build"

tar_paths='/tmp/tar_paths.txt'

find . \
    -type f \
    -name '+*' \
    -mindepth 1 \
    -exec \
        sh -c 'echo ${0#./}' "{}" >>"$tar_paths" \
    \;

find . \
    -name '+*' -prune -o \
    -type d \
    -mindepth 1 \
    -maxdepth 1 \
    -exec \
        echo "{}" >>"$tar_paths" \
    \;

if [ "$rocklet_log_level" = 'debug' ]; then
    echo 'tar_paths.txt:'
    cat "$tar_paths"
fi

mkdir -p "$rocklet_artifact"

bsdtar \
    --zstd \
    -c \
    -P \
    -f "$artifact" \
    -s "#^\\.##" \
    -T "$tar_paths"

clean
