#!/bin/bash
unset IFS
set -euo pipefail

ROCKHOPPER_LOG_LEVEL="${ROCKHOPPER_LOG_LEVEL:-info}"
ROCKHOPPER_IMAGE="${ROCKHOPPER_IMAGE:-unknown image}"
ROCKHOPPER_NAME="${ROCKHOPPER_NAME:-}"
ROCKHOPPER_VERSION="${ROCKHOPPER_VERSION:-}"
ROCKHOPPER_REV="${ROCKHOPPER_REV:-}"
ROCKHOPPER_COPYRIGHT="${ROCKHOPPER_COPYRIGHT:-}"
ROCKHOPPER_LICENSE="${ROCKHOPPER_LICENSE:-}"
ROCKHOPPER_MOUNT="${ROCKHOPPER_MOUNT:-/mnt/rockhopper}"
ROCKHOPPER_DATA="${ROCKHOPPER_DATA:-"$ROCKHOPPER_MOUNT/rockhopper-data"}"
ROCKHOPPER_SPECS="${ROCKHOPPER_SPECS:-"$HOME/rockhopper-specs"}"
ROCKHOPPER_PKGMK_BUILD="${ROCKHOPPER_PKGMK_BUILD:-/tmp/crux}"
ROCKHOPPER_ARCH="${ROCKHOPPER_ARCH:-"$(uname -m)"}"
ROCKHOPPER_ARTIFACT="${ROCKHOPPER_ARTIFACT:-"$ROCKHOPPER_MOUNT/.rockhopper/crux-$ROCKHOPPER_ARCH"}"

# Forward rockhopper environment variables to Jinja
for K in $(compgen -v | grep '^ROCKHOPPER_'); do
    export "$K"
done

usage() {
    printf "Usage: %s [<OPTION>]\n" "$0"
    printf "\n"
    printf -- "--debug -d\tIncrease logging\n"
    printf -- "--quiet -q\tReduce logging\n"
    printf -- "--help -h\tShow usage menu\n"
    printf -- "--version -V\tShow version banner\n"
}

banner() {
    echo "$0 0.0.9"
}

while [ "$#" -ge 1 ]; do
    case "$1" in
    '--debug' | '-d')
        shift
        ROCKHOPPER_LOG_LEVEL='debug'
        ;;
    '--quiet' | 'q')
        shift
        ROCKHOPPER_LOG_LEVEL='quiet'
        ;;
    '--help' | '-h')
        usage
        exit
        ;;
    '--version' | '-V')
        banner
        exit
        ;;
    *)
        usage
        exit 1
        ;;
    esac
done

if [ "$ROCKHOPPER_LOG_LEVEL" = 'debug' ]; then
    env | grep '^ROCKHOPPER_' | sort
    set -x
fi

validate() {
    REQUIRED_ENV_VARS=(
        ROCKHOPPER_NAME
        ROCKHOPPER_VERSION
        ROCKHOPPER_REV
        ROCKHOPPER_MOUNT
        ROCKHOPPER_DATA
        ROCKHOPPER_SPECS
        ROCKHOPPER_ARTIFACT
        ROCKHOPPER_PKGMK_BUILD
        ROCKHOPPER_ARCH
    )

    for REQUIRED_ENV_VAR in "${REQUIRED_ENV_VARS[@]}"; do
        eval "REQUIRED_ENV_VAL=\$$REQUIRED_ENV_VAR"

        if [ -z "$REQUIRED_ENV_VAL" ]; then
            echo "error: ${ROCKHOPPER_IMAGE} blank/missing env var: ${REQUIRED_ENV_VAR}"
            exit 1
        fi
    done
}

clean() {
    rm -rf "$ROCKHOPPER_PKGMK_BUILD"
}

validate
clean

LIC=''

if [ -n "$ROCKHOPPER_COPYRIGHT" ]; then
    LIC="Copyright: $ROCKHOPPER_COPYRIGHT"
fi

if [ -n "$ROCKHOPPER_LICENSE" ]; then
    LIC="${LIC}\nLicense: $ROCKHOPPER_LICENSE"
fi

FILES="$ROCKHOPPER_PKGMK_BUILD/files"
mkdir -p "$FILES"
printf "$LIC\n" >"$FILES/LICENSE"

DATA="$FILES/data"
mkdir -p "$DATA"
cp -r "$ROCKHOPPER_DATA/"* "$DATA"

cd "$ROCKHOPPER_DATA"

PKGMK_SOURCE="${FILES}/LICENSE "
PKGMK_PACKAGE=''

for f in $(find . -print); do
    f="${f#./}"

    if [ "$f" = '.' ]; then
        continue
    fi

    if [ -d "$f" ]; then
        PKGMK_PACKAGE="${PKGMK_PACKAGE}mkdir -p \"\${PKG}/$f\"; "
    elif [ -f "$f" ]; then
        PKGMK_SOURCE="${PKGMK_SOURCE}${FILES}/data/$f "
        b="$(basename "$f")"
        PKGMK_PACKAGE="${PKGMK_PACKAGE}install \"$b\" \"\${PKG}/$f\"; "
    else
        echo "error: ${ROCKHOPPER_IMAGE}: unsupported file system file type for path: ${f}"
    fi
done

export PKGMK_SOURCE
export PKGMK_PACKAGE

PKGFILE="$ROCKHOPPER_PKGMK_BUILD/Pkgfile"
rsubst "$ROCKHOPPER_SPECS/Pkgfile.j2" >"$PKGFILE"

if [ "$ROCKHOPPER_LOG_LEVEL" = 'debug' ]; then
    echo "Pkgfile:"
    cat "$PKGFILE"
fi

ARTIFACT="$ROCKHOPPER_PKGMK_BUILD/$ROCKHOPPER_NAME#$ROCKHOPPER_VERSION-$ROCKHOPPER_REV.pkg.tar.gz"

cd "$ROCKHOPPER_PKGMK_BUILD"

pkgmk() {
    if [ "$ROCKHOPPER_LOG_LEVEL" = 'quiet' ]; then
        command pkgmk "$@" >/dev/null 2>&1
    else
        command pkgmk "$@"
    fi
}

pkgmk -kw

mkdir -p "$ROCKHOPPER_ARTIFACT"
cp "$ARTIFACT" "$ROCKHOPPER_ARTIFACT"

clean
