#!/bin/bash
unset IFS
set -euo pipefail

rocklet_log_level="${rocklet_log_level:-info}"
rocklet_image="${rocklet_image:-unknown image}"
rocklet_mount_path="${rocklet_mount_path:-/mnt/rockhopper}"
rocklet_maintainer="${rocklet_maintainer:-}"
rocklet_name="${rocklet_name:-}"
rocklet_version="${rocklet_version:-}"
rocklet_rev="${rocklet_rev:-}"
rocklet_license="${rocklet_license:-}"
rocklet_templates="${rocklet_templates:-"$HOME/templates"}"
rocklet_cache="${rocklet_cache:-"$rocklet_mount_path/.rockhopper"}"
rocklet_artifact="${rocklet_artifact:-"$rocklet_cache/artifacts/alpine-linux"}"
rocklet_apk_build="${rocklet_apk_build:-/tmp/alpine-linux}"
rocklet_os_arch="${rocklet_os_arch:-"$(uname -m)"}"
rocklet_apk_make_depends="${rocklet_apk_make_depends:-}"
rocklet_apk_check_depends="${rocklet_apk_check_depends:-}"
rocklet_apk_source="${rocklet_apk_source:-}"

# Forward rockhopper environment variables to Jinja
for K in $(compgen -v | grep '^rocklet_'); do
    export "$K"
done

usage() {
    printf "Usage: %s [<OPTION>]\n" "$0"
    printf "\n"
    printf -- "--debug -d\tIncrease logging\n"
    printf -- "--quiet -q\tReduce logging\n"
    printf -- "--help -h\tShow usage menu\n"
    printf -- "--version -V\tShow version banner\n"
}

ROCKHOPPER_VERSION='0.0.15'
ROCKHOPPER_REV='1'

banner() {
    echo "$0 $ROCKHOPPER_VERSION-$ROCKHOPPER_REV"
}

while [ "$#" -ge 1 ]; do
    case "$1" in
    '--debug' | '-d')
        shift
        rocklet_log_level='debug'
        ;;
    '--quiet' | 'q')
        shift
        rocklet_log_level='quiet'
        ;;
    '--help' | '-h')
        usage
        exit
        ;;
    '--version' | '-V')
        banner
        exit
        ;;
    *)
        usage
        exit 1
        ;;
    esac
done

if [ "$rocklet_log_level" = 'debug' ]; then
    env | grep '^rocklet_' | sort
    set -x
fi

validate() {
    required_env_vars=(
        rocklet_apk_build
        rocklet_artifact
        rocklet_cache
        rocklet_image
        rocklet_license
        rocklet_log_level
        rocklet_mount_path
        rocklet_name
        rocklet_os_arch
        rocklet_rev
        rocklet_templates
        rocklet_version
    )

    for required_env_var in "${required_env_vars[@]}"; do
        eval "required_env_val=\$$required_env_var"

        if [ -z "$required_env_val" ]; then
            echo "error: ${rocklet_image}: blank/missing env var: ${required_env_var}"
            exit 1
        fi
    done
}

clean() {
    rm -rf "$rocklet_apk_build"
}

validate
clean

export source_media="$rocklet_cache/source-media"
mkdir -p "$source_media"

src="$rocklet_apk_build/src"
mkdir -p "$src/usr/share/licenses/$rocklet_name"

COPYING="$src/usr/share/licenses/$rocklet_name/COPYING"
rsubst --strict "$rocklet_templates/COPYING.j2" >"$COPYING"

if [ "$rocklet_log_level" = 'debug' ]; then
    echo "COPYING:"
    cat "$COPYING"
fi

cp -r "$source_media"/* "$src"

cd "$source_media"

apk_package=''

for f in $(find . -print); do
    f="${f#./}"

    if [ "$f" = '' ]; then
        continue
    fi

    if [ -d "$f" ]; then
        apk_package="${apk_package}mkdir -p \"\$pkgdir/$f\"; "
    elif [ -f "$f" ]; then
        apk_package="${apk_package}cp \"\$srcdir/$f\" \"\$pkgdir/$f\""
    else
        echo "error: ${rocklet_image}: unsupported file system file type for path: ${source_media}/${f}"
        exit 1
    fi
done

export apk_package

mkdir -p "$rocklet_apk_build/$rocklet_name"
APKBUILD="$rocklet_apk_build/$rocklet_name/APKBUILD"
rsubst --strict "$rocklet_templates/APKBUILD.j2" >"$APKBUILD"

if [ "$rocklet_log_level" = 'debug' ]; then
    echo "APKBUILD:"
    cat "$APKBUILD"
fi

mkdir -p "$rocklet_apk_build/$rocklet_name/src"

cd "$rocklet_apk_build/$rocklet_name"

abuild() {
    if [ "$rocklet_log_level" = 'quiet' ]; then
        command abuild -q "$@" 2>/dev/null 1>&2
    elif [ "$rocklet_log_level" = 'debug' ]; then
        command abuild -v "$@"
    else
        command abuild "$@"
    fi
}

abuild -F checksum
abuild -F -r

mkdir -p "$rocklet_artifact"

cp \
    "/root/packages/alpine-linux/$(uname -m)/$rocklet_name-$rocklet_version-r$rocklet_rev.apk" \
    "$rocklet_artifact/$rocklet_name-$rocklet_version-r$rocklet_rev.$rocklet_os_arch.apk"

clean
