#!/bin/bash
unset IFS
set -euo pipefail

rocklet_log_level="${rocklet_log_level:-info}"
rocklet_image="${rocklet_image:-unknown image}"
rocklet_mount_path="${rocklet_mount_path:-/mnt/rockhopper}"
rocklet_name="${rocklet_name:-}"
rocklet_version="${rocklet_version:-}"
rocklet_rev="${rocklet_rev:-}"
rocklet_copyright="${rocklet_copyright:-}"
rocklet_license="${rocklet_license:-}"
rocklet_data="${rocklet_data:-"$rocklet_mount_path/rockhopper-data"}"
rocklet_specs="${rocklet_specs:-"$HOME/rockhopper-specs"}"
rocklet_cache="${rocklet_cache:-"$rocklet_mount_path/.rockhopper"}"
rocklet_artifact="${rocklet_artifact:-"$rocklet_cache/alpine-linux"}"
rocklet_apk_build="${rocklet_apk_build:-/tmp/alpine-linux}"
rocklet_os_arch="${rocklet_os_arch:-"$(uname -m)"}"

# Forward rockhopper environment variables to Jinja
for K in $(compgen -v | grep '^rocklet_'); do
    export "$K"
done

usage() {
    printf "Usage: %s [<OPTION>]\n" "$0"
    printf "\n"
    printf -- "--debug -d\tIncrease logging\n"
    printf -- "--quiet -q\tReduce logging\n"
    printf -- "--help -h\tShow usage menu\n"
    printf -- "--version -V\tShow version banner\n"
}

banner() {
    echo "$0 0.0.11"
}

while [ "$#" -ge 1 ]; do
    case "$1" in
    '--debug' | '-d')
        shift
        rocklet_log_level='debug'
        ;;
    '--quiet' | 'q')
        shift
        rocklet_log_level='quiet'
        ;;
    '--help' | '-h')
        usage
        exit
        ;;
    '--version' | '-V')
        banner
        exit
        ;;
    *)
        usage
        exit 1
        ;;
    esac
done

if [ "$rocklet_log_level" = 'debug' ]; then
    env | grep '^rocklet_' | sort
fi

validate() {
    required_env_vars=(
        rocklet_apk_build
        rocklet_artifact
        rocklet_cache
        rocklet_data
        rocklet_image
        rocklet_license
        rocklet_log_level
        rocklet_mount_path
        rocklet_name
        rocklet_os_arch
        rocklet_rev
        rocklet_specs
        rocklet_version
    )

    for required_env_var in "${required_env_vars[@]}"; do
        eval "required_env_val=\$$required_env_var"

        if [ -z "$required_env_val" ]; then
            echo "error: ${rocklet_image}: blank/missing env var: ${required_env_var}"
            exit 1
        fi
    done
}

clean() {
    rm -rf "$rocklet_apk_build"
}

validate
clean

apk_license=''

if [ -n "$rocklet_copyright" ]; then
    apk_license="$rocklet_copyright"
fi

apk_license="$apk_license\\n$rocklet_license"
export apk_license

cd "$rocklet_data"

apk_package=''

for f in $(find . -print); do
    f="${f#./}"

    if [ "$f" = '' ]; then
        continue
    fi

    if [ -d "$f" ]; then
        apk_package="${apk_package}mkdir -p \"\$pkgdir/$f\"; "
    elif [ -f "$f" ]; then
        apk_package="${apk_package}cp \"\$srcdir/$f\" \"\$pkgdir/$f\""
    else
        echo "error: ${rocklet_image}: unsupported file system file type for path: ${rocklet_data}/${f}"
        exit 1
    fi
done

export apk_package

mkdir -p "$rocklet_apk_build/$rocklet_name"
APKBUILD="$rocklet_apk_build/$rocklet_name/APKBUILD"
rsubst "$rocklet_specs/APKBUILD.j2" >"$APKBUILD"

if [ "$rocklet_log_level" = 'debug' ]; then
    echo "APKBUILD:"
    cat "$APKBUILD"
fi

src="$rocklet_apk_build/$rocklet_name/src"
mkdir -p "$src"

cd "$rocklet_apk_build/$rocklet_name"

abuild() {
    if [ "$rocklet_log_level" = 'quiet' ]; then
        command abuild "$@" 2>/dev/null 1>&2
    else
        command abuild "$@"
    fi
}

abuild -F checksum
abuild -F -r

mkdir -p "$rocklet_artifact"

cp \
    "/root/packages/alpine-linux/$(uname -m)/$rocklet_name-$rocklet_version-r$rocklet_rev.apk" \
    "$rocklet_artifact/$rocklet_name-$rocklet_version-r$rocklet_rev.$rocklet_os_arch.apk"

clean
