#!/bin/ash
unset IFS
set -euo pipefail

usage() {
    printf "Usage: %s <OPTIONS>\n" "$0"
    printf "\n"
    printf -- "--name <name>\t\t\tPackage name (Required, nonblank).\n"
    printf -- "--version <version>\t\tPackage version (Required, nonblank).\n"
    printf -- "--release <release>\t\tPackage release version (Required, nonblank).\n"
    printf -- "--arch <architecture>\t\tPackage architecture (Required, nonblank).\n"
    printf -- "--maintainer <maintainer>\tPackage maintainer of the form \"<name> <email>\" (Required, RFC822 format).\n"
    printf -- "--summary <summary>\t\tPackage summary (Ignored).\n"
    printf -- "--description <description>\tPackage description (Required, nonblank).\n"
    printf -- "--copyright <copyright>\tPackage copyright (Optional).\n"
    printf -- "--license <license>\t\tPackage license (Required, nonblank).\n"
    printf -- "--dependencies <dependencies>\tPrerequisite package constraints (Optional).\n"
    printf -- "--changelog-file <path>\tChangelog location (Ignored).\n"
    printf -- "--url <homepage>\t\tPackage homepage (Required, nonblank).\n"
    printf -- "--help\t\t\t\tShow usage menu.\n"
}

ROCKHOPPER_DATA_DIR='rockhopper-data'
ARTIFACT_DIR='.rockhopper/alpine'

clean() {
    rm -rf alpinelinux
}

while [ "$#" -ge 1 ]; do
    case "$1" in
    '--help')
        usage
        exit
        ;;
    '--name')
        shift
        export NAME="$1"
        shift
        ;;
    '--version')
        shift
        export VERSION="$1"
        shift
        ;;
    '--release')
        shift
        export RELEASE="$1"
        shift
        ;;
    '--arch')
        shift
        export ARCH="$1"
        shift
        ;;
    '--maintainer')
        shift
        export MAINTAINER="$1"
        shift
        ;;
    '--summary')
        shift
        shift
        ;;
    '--description')
        shift
        export DESCRIPTION="$1"
        shift
        ;;
    '--copyright')
        shift
        export COPYRIGHT="$1"
        shift
        ;;
    '--license')
        shift
        export LICENSE="$1"
        shift
        ;;
    '--dependencies')
        shift
        export DEPENDENCIES="$1"
        shift
        ;;
    '--changelog-file')
        shift
        shift
        ;;
    '--url')
        shift
        export URL="$1"
        shift
        ;;
    *)
        usage
        exit 1
        ;;
    esac
done

validate() {
    if [ "${NAME:-}" = '' ]; then
        echo "error: blank/missing --name <name>"
        usage
        exit 1
    fi

    if [ "${VERSION:-}" = '' ]; then
        echo "error: blank/missing --version <version>"
        usage
        exit 1
    fi

    if [ "${RELEASE:-}" = '' ]; then
        echo "error: blank/missing --release <release>"
        usage
        exit 1
    fi

    if [ "${ARCH:-}" = '' ]; then
        echo "error: blank/missing --arch <architecture>"
        usage
        exit 1
    fi

    if [ "${MAINTAINER:-}" = '' ]; then
        echo "error: blank/missing --maintainer <maintainer>"
        usage
        exit 1
    fi

    if [ "${DESCRIPTION:-}" = '' ]; then
        echo "error: blank/missing --description <description>"
        usage
        exit 1
    fi

    if [ "${LICENSE:-}" = '' ]; then
        echo "error: blank/missing --license <license>"
        usage
        exit 1
    fi

    if [ "${URL:-}" = '' ]; then
        echo "error: blank/missing --url <homepage>"
        usage
        exit 1
    fi
}

validate

cd /src

INTERNAL_DIR="alpinelinux/$NAME"

LIC=""

if [ "${COPYRIGHT:-}" != '' ]; then
    LIC="$COPYRIGHT"
fi

LIC="$LIC
$LICENSE"
printf "$LIC\n" >/tmp/LICENSE

clean
mkdir -p "$INTERNAL_DIR"

APKBUILD="# Maintainer: $MAINTAINER
pkgname=$NAME
pkgver=$VERSION
pkgrel=$RELEASE
pkgdesc=\"$DESCRIPTION\"
url=\"$URL\"
arch=\"$ARCH\"
license=\"$LICENSE\"
depends=\"${DEPENDENCIES:-}\"
makedepends=\"\"
checkdepends=\"\"
install=\"\"
subpackages=\"\"
source=\"\"
builddir=\"\$srcdir/\"
options=\"!check\"

prepare() {
    default_prepare
    cp -r /src/$ROCKHOPPER_DATA_DIR/* \"\$builddir\"
    mkdir -p \"\$builddir/usr/share/licenses/$NAME\"
    cp /tmp/LICENSE \"\$builddir/usr/share/licenses/$NAME\"
}

package() {
    mkdir -p \"\$pkgdir/usr/share/licenses/$NAME\"
    cp \"\$srcdir/usr/share/licenses/$NAME/LICENSE\" \"\$pkgdir/usr/share/licenses/$NAME/LICENSE\"
"

cd "$ROCKHOPPER_DATA_DIR"
for f in $(find . -print); do
    f="${f#./}"

    if [ "$f" = '.' ]; then
        continue
    fi

    if [ -d "$f" ]; then
        APKBUILD="$APKBUILD\n    mkdir -p \"\$pkgdir/$f\""
    elif [ -f "$f" ]; then
        APKBUILD="$APKBUILD\n    cp \"\$srcdir/$f\" \"\$pkgdir/$f\""
    else
        echo "error: unsupported file system file type for path: $ROCKHOPPER_DATA_DIR/$f"
        exit 1
    fi
done
cd ..

APKBUILD="$APKBUILD\n}"

printf "$APKBUILD\n" >"$INTERNAL_DIR/APKBUILD"

SRC_DIR="$INTERNAL_DIR/src"
mkdir -p "$SRC_DIR"

cd "$INTERNAL_DIR"
abuild -F checksum
abuild -F -r
cd /src

mkdir -p "$ARTIFACT_DIR"
cp "/root/packages/alpinelinux/$(uname -m)/$NAME-$VERSION-r$RELEASE.apk" "$ARTIFACT_DIR/$NAME-$VERSION-r$RELEASE.$ARCH.apk"

clean
