#!/bin/bash
unset IFS
set -euo pipefail

ROCKHOPPER_QUIET="${ROCKHOPPER_QUIET:-0}"
ROCKHOPPER_DEBUG="${ROCKHOPPER_DEBUG:-0}"
ROCKHOPPER_IMAGE="${ROCKHOPPER_IMAGE:-unknown image}"
ROCKHOPPER_NAME="${ROCKHOPPER_NAME:-}"
ROCKHOPPER_VERSION="${ROCKHOPPER_VERSION:-}"
ROCKHOPPER_REV="${ROCKHOPPER_REV:-}"
ROCKHOPPER_MAINTAINER="${ROCKHOPPER_MAINTAINER:-}"
ROCKHOPPER_DESCRIPTION="${ROCKHOPPER_DESCRIPTION:-}"
ROCKHOPPER_DEPENDENCIES="${ROCKHOPPER_DEPENDENCIES:-}"
ROCKHOPPER_COPYRIGHT="${ROCKHOPPER_COPYRIGHT:-}"
ROCKHOPPER_LICENSE="${ROCKHOPPER_LICENSE:-}"
ROCKHOPPER_MOUNT="${ROCKHOPPER_MOUNT:-/mnt/rockhopper}"
ROCKHOPPER_URL="${ROCKHOPPER_URL:-}"
ROCKHOPPER_DATA_DIR="${ROCKHOPPER_DATA_DIR:-$ROCKHOPPER_MOUNT/rockhopper-data}"
ROCKHOPPER_ARTIFACT_DIR="${ROCKHOPPER_ARTIFACT_DIR:-$ROCKHOPPER_MOUNT/.rockhopper/alpine}"
ROCKHOPPER_APK_BUILD_DIR="${ROCKHOPPER_APK_BUILD_DIR:-/tmp/alpinelinux}"
ROCKHOPPER_ARCH="${ROCKHOPPER_ARCH:-noarch}"

usage() {
    printf "Usage: %s [<OPTION>]\n" "$0"
    printf "\n"
    printf -- "--quiet \q\tReduce logging\n"
    printf -- "--debug -d\tIncrease logging\n"
    printf -- "--help -h\tShow usage menu\n"
    printf -- "--version -V\tShow version banner\n"
}

banner() {
    echo "$0 0.0.3"
}

while [ "$#" -ge 1 ]; do
    case "$1" in
    '--quiet' | 'q')
        shift
        ROCKHOPPER_QUIET='1'
        ;;
    '--debug' | '-d')
        shift
        ROCKHOPPER_DEBUG=1
        ;;
    '--help' | '-h')
        usage
        exit
        ;;
    '--version' | '-V')
        banner
        exit
        ;;
    *)
        usage
        exit 1
        ;;
    esac
done

if [ "$ROCKHOPPER_DEBUG" = 1 ]; then
    ROCKHOPPER_QUIET='0'
    env | grep '^ROCKHOPPER_' | sort
    set -x
fi

validate() {
    REQUIRED_ENV_VARS=(
        ROCKHOPPER_NAME
        ROCKHOPPER_VERSION
        ROCKHOPPER_REV
        ROCKHOPPER_DESCRIPTION
        ROCKHOPPER_LICENSE
        ROCKHOPPER_MOUNT
        ROCKHOPPER_URL
        ROCKHOPPER_DATA_DIR
        ROCKHOPPER_ARTIFACT_DIR
        ROCKHOPPER_APK_BUILD_DIR
        ROCKHOPPER_ARCH
    )

    for REQUIRED_ENV_VAR in "${REQUIRED_ENV_VARS[@]}"; do
        eval "REQUIRED_ENV_VAL=\$$REQUIRED_ENV_VAR"

        if [ -z "$REQUIRED_ENV_VAL" ]; then
            echo "error: ${ROCKHOPPER_IMAGE}: blank/missing env var: ${REQUIRED_ENV_VAR}"
            exit 1
        fi
    done
}

clean() {
    rm -rf "$ROCKHOPPER_APK_BUILD_DIR"
}

validate
clean

LIC=""

if [ -n "$ROCKHOPPER_COPYRIGHT" ]; then
    LIC="$ROCKHOPPER_COPYRIGHT"
fi

LIC="$LIC
$ROCKHOPPER_LICENSE"
printf "$LIC\n" >/tmp/LICENSE

mkdir -p "$ROCKHOPPER_APK_BUILD_DIR/$ROCKHOPPER_NAME"

APKBUILD="# Maintainer: $ROCKHOPPER_MAINTAINER
pkgname=$ROCKHOPPER_NAME
pkgver=$ROCKHOPPER_VERSION
pkgrel=$ROCKHOPPER_REV
pkgdesc=\"$ROCKHOPPER_DESCRIPTION\"
url=\"$ROCKHOPPER_URL\"
arch=\"$ROCKHOPPER_ARCH\"
license=\"$ROCKHOPPER_LICENSE\"
depends=\"$ROCKHOPPER_DEPENDENCIES\"
makedepends=\"\"
checkdepends=\"\"
install=\"\"
subpackages=\"\"
source=\"\"
builddir=\"\$srcdir/\"
options=\"!check\"

prepare() {
    default_prepare
    cp -r \"$ROCKHOPPER_DATA_DIR/\"* \"\$builddir\"
    mkdir -p \"\$builddir/usr/share/licenses/$ROCKHOPPER_NAME\"
    cp /tmp/LICENSE \"\$builddir/usr/share/licenses/$ROCKHOPPER_NAME\"
}

package() {
    mkdir -p \"\$pkgdir/usr/share/licenses/$ROCKHOPPER_NAME\"
    cp \"\$srcdir/usr/share/licenses/$ROCKHOPPER_NAME/LICENSE\" \"\$pkgdir/usr/share/licenses/$ROCKHOPPER_NAME/LICENSE\"
"

cd "$ROCKHOPPER_DATA_DIR"

for f in $(find . -print); do
    if [ "$f" = './' ]; then
        continue
    fi

    f="${f#./}"

    if [ -d "$f" ]; then
        APKBUILD="$APKBUILD\n    mkdir -p \"\$pkgdir/$f\""
    elif [ -f "$f" ]; then
        APKBUILD="$APKBUILD\n    cp \"\$srcdir/$f\" \"\$pkgdir/$f\""
    else
        echo "error: ${ROCKHOPPER_IMAGE}: unsupported file system file type for path: ${ROCKHOPPER_DATA_DIR}/${f}"
        exit 1
    fi
done

APKBUILD="$APKBUILD\n}"

printf "$APKBUILD\n" >"$ROCKHOPPER_APK_BUILD_DIR/$ROCKHOPPER_NAME/APKBUILD"

if [ "$ROCKHOPPER_DEBUG" = '1' ]; then
    echo "APKBUILD:"
    cat "$ROCKHOPPER_APK_BUILD_DIR/$ROCKHOPPER_NAME/APKBUILD"
fi

SRC_DIR="$ROCKHOPPER_APK_BUILD_DIR/$ROCKHOPPER_NAME/src"
mkdir -p "$SRC_DIR"

cd "$ROCKHOPPER_APK_BUILD_DIR/$ROCKHOPPER_NAME"

abuild -F checksum

COMMAND="abuild -F -r"

if [ "$ROCKHOPPER_QUIET" = 1 ]; then
    $COMMAND >/dev/null
else
    $COMMAND
fi

mkdir -p "$ROCKHOPPER_ARTIFACT_DIR"
cp "/root/packages/alpinelinux/$(uname -m)/$ROCKHOPPER_NAME-$ROCKHOPPER_VERSION-r$ROCKHOPPER_REV.apk" "$ROCKHOPPER_ARTIFACT_DIR/$ROCKHOPPER_NAME-$ROCKHOPPER_VERSION-r$ROCKHOPPER_REV.$ROCKHOPPER_ARCH.apk"
clean
