# log_level = "info"
# log_level = "debug"
log_level = "quiet"

# docker_args = []

[rocklet]
name = "raygun"
identifier = "test.mars.raygun"
version = "0.0.1"
rev = "1"
maintainer = "Marvin the Martian <marvin@mars.test>"
manufacturer = "Mars Corp"
summary = "Space modulator"
description = "Illudium Q-36 explosive space modulator"
copyright = "Copyright (C) 1948 Marvin the Martian"
license = "0BSD"
url = "https://mars.test/"

# [docker_env]
# key = "value"

[[pkg]]
image = "n4jm4/rockhopper:alpine-linux"
rocklet.oci_arch = "linux/amd64"
rocklet.os_arch = "x86_64"
# rocklet.dependencies = "bash"
# rocklet.apk_makedepends = "gcc"
# rocklet.apk_checkdepends = "diff"
dest."usr/bin" = "bin/linux/amd64"

[[pkg]]
image = "n4jm4/rockhopper:alpine-linux"
rocklet.oci_arch = "linux/arm64"
rocklet.os_arch = "aarch64"
# rocklet.dependencies = "bash"
# rocklet.apk_makedepends = "gcc"
# rocklet.apk_checkdepends = "diff"
dest."usr/bin" = "bin/linux/arm64"

[[pkg]]
image = "n4jm4/rockhopper:fedora"
rocklet.oci_arch = "linux/amd64"
rocklet.os_arch = "x86_64"
# rocklet.dependencies = "bash"
# rocklet.pkg_licenselogic = "single"
dest."usr/bin" = "bin/linux/amd64"

[[pkg]]
image = "n4jm4/rockhopper:fedora"
rocklet.oci_arch = "linux/arm64"
rocklet.os_arch = "aarch64"
# rocklet.dependencies = "bash"
# rocklet.pkg_licenselogic = "single"
dest."usr/bin" = "bin/linux/arm64"

[[pkg]]
image = "n4jm4/rockhopper:freebsd"
rocklet.origin = "local/raygun"
rocklet.oci_arch = "linux/amd64"
rocklet.os_arch = "freebsd:*:amd64"
# rocklet.dependencies = "bash: { origin: \"shells/bash\" }"
# rocklet.pkg_prefix = "/usr/local"
dest."usr/local/bin" = "bin/freebsd/amd64"

[[pkg]]
image = "n4jm4/rockhopper:freebsd"
rocklet.origin = "local/raygun"
rocklet.oci_arch = "linux/arm64"
rocklet.os_arch = "freebsd:*:arm64"
# rocklet.dependencies = "bash: { origin: \"shells/bash\" }"
# rocklet.pkg_prefix = "/usr/local"
dest."usr/local/bin" = "bin/freebsd/arm64"

[[pkg]]
image = "n4jm4/rockhopper:macos"
rocklet.oci_arch = "linux/amd64"
rocklet.os_arch = "x86_64"
# rocklet.dependencies = "bash"
#
# macOS user:staff
#
# rocklet.uid = "501"
# rocklet.gid = "20"
# dest."Applications/raygun.app" = "raygun.app"
#
# macOS root:wheel
#
# rocklet.uid = "0"
# rocklet.gid = "0"
dest."usr/local/bin" = "bin/darwin/amd64"

[[pkg]]
image = "n4jm4/rockhopper:macos"
rocklet.oci_arch = "linux/arm64"
rocklet.os_arch = "arm64"
# rocklet.dependencies = "bash"
#
# macOS user:staff
#
# rocklet.uid = "501"
# rocklet.gid = "20"
# dest."Applications/raygun.app" = "raygun.app"
#
# macOS root:wheel
#
# rocklet.uid = "0"
# rocklet.gid = "0"
dest."usr/local/bin" = "bin/darwin/arm64"

[[pkg]]
image = "n4jm4/rockhopper:netbsd"
rocklet.oci_arch = "linux/amd64"
rocklet.os_arch = "x86_64"
# rocklet.dependencies = "bash"
# rocklet.pkg_opsys = "NetBSD"
rocklet.pkg_os_version = "10.1"
# byte estimate, including dependencies
rocklet.pkg_size_all = "1000"
# rocklet.pkg_localbase = "/usr/pkg"
dest."bin" = "bin/netbsd/amd64"

[[pkg]]
image = "n4jm4/rockhopper:netbsd"
rocklet.oci_arch = "linux/arm64"
rocklet.os_arch = "aarch64"
# rocklet.dependencies = "bash"
# rocklet.pkg_opsys = "NetBSD"
rocklet.pkg_os_version = "10.1"
# byte estimate, including dependencies
rocklet.pkg_size_all = "1000"
# rocklet.pkg_localbase = "/usr/pkg"
dest."bin" = "bin/netbsd/arm64"

[[pkg]]
image = "n4jm4/rockhopper:ubuntu"
rocklet.oci_arch = "linux/amd64"
rocklet.os_arch = "amd64"
# rocklet.dependencies = "bash"
# rocklet.apt_priority = "optional"
dest."usr/bin" = "bin/linux/amd64"

[[pkg]]
image = "n4jm4/rockhopper:ubuntu"
rocklet.oci_arch = "linux/arm64"
rocklet.os_arch = "arm64"
# rocklet.dependencies = "bash"
# rocklet.apt_priority = "optional"
dest."usr/bin" = "bin/linux/arm64"

[[pkg]]
image = "n4jm4/rockhopper:test-windows"
rocklet.oci_arch = "linux/amd64"
rocklet.os_arch = "x64"
rocklet.msi_upgrade_code = "69F159AD-CE9C-4EE8-A25D-BB4E8A226D73"
# rocklet_msi_lcid = "1033"
# rocklet.msi_codepage = "1252"
dest."bin" = "bin/windows/amd64"

[[pkg]]
image = "n4jm4/rockhopper:test-windows"
rocklet.oci_arch = "linux/arm64"
rocklet.os_arch = "arm64"
rocklet.msi_upgrade_code = "69F159AD-CE9C-4EE8-A25D-BB4E8A226D73"
# rocklet_msi_lcid = "1033"
# rocklet.msi_codepage = "1252"
dest."bin" = "bin/windows/arm64"
