#!/bin/bash
unset IFS
set -euo pipefail

usage() {
    printf "Usage: %s <OPTIONS>\n" "$0"
    printf "\n"
    printf -- "--name <name>\t\t\tPackage name (Required, nonblank).\n"
    printf -- "--version <version>\t\tPackage version (Required, nonblank).\n"
    printf -- "--release <release>\t\tPackage release version (Required, nonblank).\n"
    printf -- "--arch <architecture>\t\tPackage architecture (Required, nonblank).\n"
    printf -- "--maintainer <maintainer>\tPackage maintainer of the form \"<name> <email>\" (Required, RFC822 format).\n"
    printf -- "--summary <summary>\t\tPackage summary (Required, nonblank).\n"
    printf -- "--description <description>\tPackage description (Required, nonblank).\n"
    printf -- "--copyright <copyright>\t\tPackage copyright (Optional).\n"
    printf -- "--license <license>\t\tPackage license (Required, nonblank).\n"
    printf -- "--dependencies <dependencies>\tPrerequisite package constraints (Optional).\n"
    printf -- "--changelog-file <path>\t\tChangelog location (Required, nonblank).\n"
    printf -- "--url <homepage>\t\tPackage homepage (Optional).\n"
    printf -- "--help\t\t\t\tShow usage menu.\n"
    printf -- "-V\t\t\t\tShow version banner.\n"
}

banner() {
    echo 'rockhopper 0.0.2'
}

ROCKHOPPER_MOUNT='/mnt/rockhopper'
ROCKHOPPER_DATA_DIR="$ROCKHOPPER_MOUNT/rockhopper-data"
ROCKHOPPER_ARTIFACT_DIR="$ROCKHOPPER_MOUNT/.rockhopper/fedora"
RPM_BUILD_DIR='/root/rpmbuild'

clean() {
    rm -rf "$RPM_BUILD_DIR"
}

while [ "$#" -ge 1 ]; do
    case "$1" in
    '--help')
        usage
        exit
        ;;
    '-V')
        banner
        exit
        ;;
    '--name')
        shift
        export NAME="$1"
        shift
        ;;
    '--version')
        shift
        export VERSION="$1"
        shift
        ;;
    '--release')
        shift
        export RELEASE="$1"
        shift
        ;;
    '--arch')
        shift
        export ARCH="$1"
        shift
        ;;
    '--maintainer')
        shift
        export MAINTAINER="$1"
        shift
        ;;
    '--summary')
        shift
        export SUMMARY="$1"
        shift
        ;;
    '--description')
        shift
        export DESCRIPTION="$1"
        shift
        ;;
    '--copyright')
        shift
        export COPYRIGHT="$1"
        shift
        ;;
    '--license')
        shift
        export LICENSE="$1"
        shift
        ;;
    '--dependencies')
        shift
        export DEPENDENCIES="$1"
        shift
        ;;
    '--changelog-file')
        shift
        export CHANGELOG_PATH="$1"
        shift
        ;;
    '--url')
        shift
        export URL="$1"
        shift
        ;;
    *)
        usage
        exit 1
        ;;
    esac
done

validate() {
    if [ -z "${NAME:-}" ]; then
        echo "error: blank/missing --name <name>"
        usage
        exit 1
    fi

    if [ -z "${VERSION:-}" ]; then
        echo "error: blank/missing --version <version>"
        usage
        exit 1
    fi

    if [ -z "${RELEASE:-}" ]; then
        echo "error: blank/missing --release <release>"
        usage
        exit 1
    fi

    if [ -z "${ARCH:-}" ]; then
        echo "error: blank/missing --arch <architecture>"
        usage
        exit 1
    fi

    if [ -z "${MAINTAINER:-}" ]; then
        echo "error: blank/missing --maintainer <maintainer>"
        usage
        exit 1
    fi

    if [ -z "${SUMMARY:-}" ]; then
        echo "error: blank/missing --summary <summary>"
        usage
        exit 1
    fi

    if [ -z "${DESCRIPTION:-}" ]; then
        echo "error: blank/missing --description <description>"
        usage
        exit 1
    fi

    if [ -z "${LICENSE:-}" ]; then
        echo "error: blank/missing --license <license>"
        usage
        exit 1
    fi

    if [ -z "${CHANGELOG_PATH:-}" ]; then
        echo "error: blank/missing --changelog-file <path>"
        usage
        exit 1
    fi
}

validate
clean

LIC=""

if [ -n "${COPYRIGHT:-}" ]; then
    LIC="$COPYRIGHT"
fi

LIC="$LIC
$LICENSE"
printf "$LIC\n" >/tmp/LICENSE

BANNER="${NAME}-${VERSION}"
mkdir -p "$RPM_BUILD_DIR/RHEL"
mkdir -p "$RPM_BUILD_DIR/$BANNER/data/usr/share/licenses/$NAME"
cp /tmp/LICENSE "$RPM_BUILD_DIR/$BANNER/data/usr/share/licenses/$NAME/LICENSE"
cp -r "$ROCKHOPPER_DATA_DIR"/* "$RPM_BUILD_DIR/$BANNER/data"

cd "$RPM_BUILD_DIR"

tar czf "$BANNER.tar.gz" "$BANNER"

mkdir -p "$RPM_BUILD_DIR/SOURCES"
mv "$RPM_BUILD_DIR/$BANNER.tar.gz" "$RPM_BUILD_DIR/SOURCES"
rm -rf "${RPM_BUILD_DIR:?}/${BANNER:?}"

SPEC="Name: $NAME
Version: $VERSION
Release: $RELEASE%%{?dist}
Summary: $SUMMARY"

if [ -n "${URL:-}" ]; then
    SPEC="$SPEC
URL: $URL"
fi

SPEC="$SPEC
BuildArch: $ARCH
License: $LICENSE"

if [ -n "${DEPENDENCIES:-}" ]; then
    SPEC="$SPEC\nRequires: $DEPENDENCIES"
fi

SPEC="$SPEC
Source0: $BANNER.tar.gz

%%description
$DESCRIPTION

%%prep
%%setup -q

%%build
# All assets prebuilt

%%install
mkdir -p \"%%{buildroot}/usr/share/licenses/$NAME\"
cp /tmp/LICENSE \"%%{buildroot}/usr/share/licenses/$NAME/LICENSE\"
"

cd "$ROCKHOPPER_DATA_DIR"

for f in $(find . -print); do
    if [ "$f" = './' ]; then
        continue
    fi

    f="${f#./}"

    if [ -d "$f" ]; then
        SPEC="$SPEC\nmkdir -p \"%%{buildroot}/$f\""
    elif [ -f "$f" ]; then
        SPEC="$SPEC\ncp \"$ROCKHOPPER_DATA_DIR/$f\" \"%%{buildroot}/$f\""
    else
        echo "error: unsupported file system file type for path: $ROCKHOPPER_DATA_DIR/$f"
        exit 1
    fi
done

SPEC="$SPEC\n%%files
/usr/share/licenses/$NAME/LICENSE
"

for f in $(find . -type f -print); do
    f="${f#./}"
    SPEC="$SPEC\n/$f"
done

cd "$ROCKHOPPER_MOUNT"

SPEC="$SPEC
%%changelog
$(cat "$CHANGELOG_PATH")"

cd "$RPM_BUILD_DIR"

mkdir -p "$RPM_BUILD_DIR/SPECS"
SPEC_PATH="$RPM_BUILD_DIR/SPECS/$NAME.spec"
printf "$SPEC\n" >"$SPEC_PATH"
rpmlint "$SPEC_PATH"
mkdir -p "$ROCKHOPPER_ARTIFACT_DIR"
rpmbuild -bb "$SPEC_PATH"
cp "$RPM_BUILD_DIR/RPMS/$ARCH/$BANNER-$RELEASE."*".$ARCH.rpm" "$ROCKHOPPER_ARTIFACT_DIR"
clean
