#!/bin/bash
unset IFS
set -euo pipefail

rocklet_log_level="${rocklet_log_level:-info}"
rocklet_image="${rocklet_image:-unknown image}"
rocklet_mount_path="${rocklet_mount_path:-/mnt/rockhopper}"
rocklet_name="${rocklet_name:-}"
rocklet_version="${rocklet_version:-}"
rocklet_rev="${rocklet_rev:-}"
rocklet_copyright="${rocklet_copyright:-}"
rocklet_license="${rocklet_license:-}"
rocklet_templates="${rocklet_templates:-"$HOME/templates"}"
rocklet_cache="${rocklet_cache:-"$rocklet_mount_path/.rockhopper"}"
rocklet_artifact="${rocklet_artifact:-"$rocklet_cache/artifacts/fedora"}"
rocklet_rpm_build="${rocklet_rpm_build:-/root/rpmbuild}"
rocklet_os_arch="${rocklet_os_arch:-"$(uname -m)"}"

# Forward rockhopper environment variables to Jinja
for K in $(compgen -v | grep '^rocklet_'); do
    export "$K"
done

usage() {
    printf "Usage: %s [<OPTION>]\n" "$0"
    printf "\n"
    printf -- "--debug -d\tIncrease logging\n"
    printf -- "--quiet -q\tReduce logging\n"
    printf -- "--help -h\tShow usage menu\n"
    printf -- "--version -V\tShow version banner\n"
}

ROCKHOPPER_VERSION='0.0.15'
ROCKHOPPER_REV='1'

banner() {
    echo "$0 $ROCKHOPPER_VERSION-$ROCKHOPPER_REV"
}

while [ "$#" -ge 1 ]; do
    case "$1" in
    '--debug' | '-d')
        shift
        rocklet_log_level='debug'
        ;;
    '--quiet' | 'q')
        shift
        rocklet_log_level='quiet'
        ;;
    '--help' | '-h')
        usage
        exit
        ;;
    '--version' | '-V')
        banner
        exit
        ;;
    *)
        usage
        exit 1
        ;;
    esac
done

if [ "$rocklet_log_level" = 'debug' ]; then
    env | grep '^rocklet_' | sort
    set -x
fi

validate() {
    required_env_vars=(
        rocklet_artifact
        rocklet_cache
        rocklet_image
        rocklet_license
        rocklet_log_level
        rocklet_mount_path
        rocklet_name
        rocklet_os_arch
        rocklet_rev
        rocklet_rpm_build
        rocklet_templates
        rocklet_version
    )

    for required_env_var in "${required_env_vars[@]}"; do
        eval "required_env_val=\$$required_env_var"

        if [ -z "$required_env_val" ]; then
            echo "error: ${rocklet_image}: blank/missing env var: ${required_env_var}"
            exit 1
        fi
    done
}

clean() {
    rm -rf "$rocklet_rpm_build"
}

validate
clean

BANNER="${rocklet_name}-${rocklet_version}"
mkdir -p "$rocklet_rpm_build/RHEL"
mkdir -p "$rocklet_rpm_build/$BANNER/data"

if [ -n "$rocklet_copyright" ]; then
    mkdir -p "$rocklet_rpm_build/$BANNER/data/usr/share/licenses/$rocklet_name"
    COPYING="$rocklet_rpm_build/$BANNER/data/usr/share/licenses/$rocklet_name/COPYING"
    rsubst --strict "$rocklet_templates/COPYING.j2" >"$COPYING"

    if [ "$rocklet_log_level" = 'debug' ]; then
        echo "COPYING:"
        cat "$COPYING"
    fi
fi

export source_media="$rocklet_cache/source-media"
mkdir -p "$source_media"
cp -r "$source_media"/* "$rocklet_rpm_build/$BANNER/data"

if [ -d "$rocklet_mount_path/.git" ]; then
    cp -r "$rocklet_mount_path/.git" "$rocklet_rpm_build/$BANNER"
fi

if [ -f "$rocklet_mount_path/changelog" ]; then
    cp "$rocklet_mount_path/changelog" "$rocklet_rpm_build/$BANNER"
fi

cd "$rocklet_rpm_build"

tar czf "$BANNER.tar.gz" "$BANNER"
mkdir -p "$rocklet_rpm_build/SOURCES"
mv "$rocklet_rpm_build/$BANNER.tar.gz" "$rocklet_rpm_build/SOURCES"
rm -rf "${rocklet_rpm_build:?}/${BANNER:?}"

export fedora_source0="${rocklet_name}-${rocklet_version}.tar.gz"

cd "$source_media"

fedora_data=''

for f in $(find . -print); do
    f="${f#./}"

    if [ "$f" = '.' ]; then
        continue
    fi

    if [ -d "$f" ]; then
        fedora_data="${fedora_data}mkdir -p \"%{buildroot}/$f\"; "
    elif [ -f "$f" ]; then
        fedora_data="${fedora_data}cp \"$source_media/$f\" \"%{buildroot}/$f\"; "
    else
        echo "error: ${rocklet_image}: unsupported file system file type for path: ${source_media}/${f}"
        exit 1
    fi
done

export fedora_data

fedora_files=''

for f in $(find . -type f -print); do
    f="${f#./}"
    fedora_files="${fedora_files}/$f "
done

export fedora_files

cd "$rocklet_rpm_build"

mkdir -p "$rocklet_rpm_build/SPECS"
SPEC="$rocklet_rpm_build/SPECS/$rocklet_name.spec"
rsubst --strict "$rocklet_templates/.spec.j2" >"$SPEC"

if [ "$rocklet_log_level" = 'debug' ]; then
    echo "SPEC:"
    cat "$SPEC"
fi

rpmbuild() {
    if [ "$rocklet_log_level" = 'quiet' ]; then
        command rpmbuild "$@" >/dev/null 2>&1
    else
        command rpmbuild "$@"
    fi
}

rpmbuild -bb "$SPEC"

mkdir -p "$rocklet_artifact"

cp \
    "${rocklet_rpm_build}/RPMS/${rocklet_os_arch}/${BANNER}-${rocklet_rev}.${rocklet_os_arch}.rpm" \
    "${rocklet_artifact}"

clean
