#!/bin/bash
unset IFS
set -euo pipefail

ROCKHOPPER_LOG_LEVEL="${ROCKHOPPER_LOG_LEVEL:-info}"
ROCKHOPPER_IMAGE="${ROCKHOPPER_IMAGE:-unknown image}"
ROCKHOPPER_NAME="${ROCKHOPPER_NAME:-}"
ROCKHOPPER_VERSION="${ROCKHOPPER_VERSION:-}"
ROCKHOPPER_REV="${ROCKHOPPER_REV:-}"
ROCKHOPPER_COPYRIGHT="${ROCKHOPPER_COPYRIGHT:-}"
ROCKHOPPER_LICENSE="${ROCKHOPPER_LICENSE:-}"
ROCKHOPPER_MOUNT="${ROCKHOPPER_MOUNT:-/mnt/rockhopper}"
ROCKHOPPER_DATA="${ROCKHOPPER_DATA:-$ROCKHOPPER_MOUNT/rockhopper-data}"
ROCKHOPPER_SPECS="${ROCKHOPPER_SPECS:-${HOME}/rockhopper-specs}"
ROCKHOPPER_ARTIFACT="${ROCKHOPPER_ARTIFACT:-$ROCKHOPPER_MOUNT/.rockhopper/fedora}"
ROCKHOPPER_RPM_BUILD="${ROCKHOPPER_RPM_BUILD:-/root/rpmbuild}"
ROCKHOPPER_ARCH="${ROCKHOPPER_ARCH:-noarch}"

# Forward rockhopper environment variables to Jinja
for K in $(compgen -v | grep '^ROCKHOPPER_'); do
    export "$K"
done

usage() {
    printf "Usage: %s [<OPTION>]\n" "$0"
    printf "\n"
    printf -- "--debug -d\tIncrease logging\n"
    printf -- "--quiet -q\tReduce logging\n"
    printf -- "--help -h\tShow usage menu\n"
    printf -- "--version -V\tShow version banner\n"
}

banner() {
    echo "$0 0.0.5"
}

while [ "$#" -ge 1 ]; do
    case "$1" in
    '--debug' | '-d')
        shift
        ROCKHOPPER_LOG_LEVEL='debug'
        ;;
    '--quiet' | 'q')
        shift
        ROCKHOPPER_LOG_LEVEL='quiet'
        ;;
    '--help' | '-h')
        usage
        exit
        ;;
    '--version' | '-V')
        banner
        exit
        ;;
    *)
        usage
        exit 1
        ;;
    esac
done

if [ "$ROCKHOPPER_LOG_LEVEL" = 'debug' ]; then
    env | grep '^ROCKHOPPER_' | sort
    set -x
fi

validate() {
    REQUIRED_ENV_VARS=(
        ROCKHOPPER_NAME
        ROCKHOPPER_VERSION
        ROCKHOPPER_REV
        ROCKHOPPER_LICENSE
        ROCKHOPPER_MOUNT
        ROCKHOPPER_DATA
        ROCKHOPPER_SPECS
        ROCKHOPPER_ARTIFACT
        ROCKHOPPER_RPM_BUILD
        ROCKHOPPER_ARCH
    )

    for REQUIRED_ENV_VAR in "${REQUIRED_ENV_VARS[@]}"; do
        eval "REQUIRED_ENV_VAL=\$$REQUIRED_ENV_VAR"

        if [ -z "$REQUIRED_ENV_VAL" ]; then
            echo "error: ${ROCKHOPPER_IMAGE}: blank/missing env var: ${REQUIRED_ENV_VAR}"
            exit 1
        fi
    done
}

clean() {
    rm -rf "$ROCKHOPPER_RPM_BUILD"
}

validate
clean

LIC=''

if [ -n "$ROCKHOPPER_COPYRIGHT" ]; then
    LIC="$ROCKHOPPER_COPYRIGHT"
fi

LIC="${LIC}\n$ROCKHOPPER_LICENSE"

export FEDORA_LICENSE='/tmp/LICENSE'
printf "$LIC\n" >"$FEDORA_LICENSE"

BANNER="${ROCKHOPPER_NAME}-${ROCKHOPPER_VERSION}"
mkdir -p "$ROCKHOPPER_RPM_BUILD/RHEL"
mkdir -p "$ROCKHOPPER_RPM_BUILD/$BANNER/data/usr/share/licenses/$ROCKHOPPER_NAME"
cp /tmp/LICENSE "$ROCKHOPPER_RPM_BUILD/$BANNER/data/usr/share/licenses/$ROCKHOPPER_NAME/LICENSE"
cp -r "$ROCKHOPPER_DATA"/* "$ROCKHOPPER_RPM_BUILD/$BANNER/data"

if [ -d "$ROCKHOPPER_MOUNT/.git" ]; then
    cp -r "$ROCKHOPPER_DATA/.git" "$ROCKHOPPER_RPM_BUILD/$BANNER"
fi

if [ -f "$ROCKHOPPER_MOUNT/changelog" ]; then
    cp "$ROCKHOPPER_MOUNT/changelog" "$ROCKHOPPER_RPM_BUILD/$BANNER"
fi

cd "$ROCKHOPPER_RPM_BUILD"

tar czf "$BANNER.tar.gz" "$BANNER"

mkdir -p "$ROCKHOPPER_RPM_BUILD/SOURCES"
mv "$ROCKHOPPER_RPM_BUILD/$BANNER.tar.gz" "$ROCKHOPPER_RPM_BUILD/SOURCES"
rm -rf "${ROCKHOPPER_RPM_BUILD:?}/${BANNER:?}"

export FEDORA_SOURCE0="${ROCKHOPPER_NAME}-${ROCKHOPPER_VERSION}.tar.gz"

cd "$ROCKHOPPER_DATA"

FEDORA_DATA=''

for f in $(find . -print); do
    f="${f#./}"

    if [ "$f" = '.' ]; then
        continue
    fi

    if [ -d "$f" ]; then
        FEDORA_DATA="${FEDORA_DATA}mkdir -p \"%{buildroot}/$f\"; "
    elif [ -f "$f" ]; then
        FEDORA_DATA="${FEDORA_DATA}cp \"$ROCKHOPPER_DATA/$f\" \"%{buildroot}/$f\"; "
    else
        echo "error: ${ROCKHOPPER_IMAGE}: unsupported file system file type for path: ${ROCKHOPPER_DATA}/${f}"
        exit 1
    fi
done

export FEDORA_DATA

FEDORA_FILES=''

for f in $(find . -type f -print); do
    f="${f#./}"
    FEDORA_FILES="${FEDORA_FILES}/$f "
done

export FEDORA_FILES

cd "$ROCKHOPPER_RPM_BUILD"

mkdir -p "$ROCKHOPPER_RPM_BUILD/SPECS"
SPEC_PATH="$ROCKHOPPER_RPM_BUILD/SPECS/$ROCKHOPPER_NAME.spec"
rsubst "$ROCKHOPPER_SPECS/.spec.j2" >"$SPEC_PATH"

if [ "$ROCKHOPPER_LOG_LEVEL" = 'debug' ]; then
    echo "SPEC:"
    cat "$SPEC_PATH"
fi

rpmbuild() {
    if [ "$ROCKHOPPER_LOG_LEVEL" = 'quiet' ]; then
        command rpmbuild "$@" >/dev/null 2>&1
    else
        command rpmbuild "$@"
    fi
}

rpmbuild -bb "$SPEC_PATH"

mkdir -p "$ROCKHOPPER_ARTIFACT"

cp \
    "${ROCKHOPPER_RPM_BUILD}/RPMS/${ROCKHOPPER_ARCH}/${BANNER}-${ROCKHOPPER_REV}.${ROCKHOPPER_ARCH}.rpm" \
    "${ROCKHOPPER_ARTIFACT}"

clean
