#!/bin/bash
unset IFS
set -euo pipefail

ROCKHOPPER_LOG_LEVEL="${ROCKHOPPER_LOG_LEVEL:-}"
ROCKHOPPER_IMAGE="${ROCKHOPPER_IMAGE:-unknown image}"
ROCKHOPPER_NAME="${ROCKHOPPER_NAME:-}"
ROCKHOPPER_VERSION="${ROCKHOPPER_VERSION:-}"
ROCKHOPPER_REV="${ROCKHOPPER_REV:-}"
ROCKHOPPER_MAINTAINER="${ROCKHOPPER_MAINTAINER:-}"
ROCKHOPPER_DESCRIPTION="${ROCKHOPPER_DESCRIPTION:-}"
ROCKHOPPER_PRIORITY="${ROCKHOPPER_PRIORITY:-optional}"
ROCKHOPPER_DEPENDENCIES="${ROCKHOPPER_DEPENDENCIES:-}"
ROCKHOPPER_COPYRIGHT="${ROCKHOPPER_COPYRIGHT:-}"
ROCKHOPPER_LICENSE="${ROCKHOPPER_LICENSE:-}"
ROCKHOPPER_MOUNT="${ROCKHOPPER_MOUNT:-/mnt/rockhopper}"
ROCKHOPPER_URL="${ROCKHOPPER_URL:-}"
ROCKHOPPER_DATA_DIR="${ROCKHOPPER_DATA_DIR:-$ROCKHOPPER_MOUNT/rockhopper-data}"
ROCKHOPPER_ARTIFACT_DIR="${ROCKHOPPER_ARTIFACT_DIR:-$ROCKHOPPER_MOUNT/.rockhopper/fedora}"
ROCKHOPPER_RPM_BUILD_DIR="${ROCKHOPPER_RPM_BUILD_DIR:-/root/rpmbuild}"
ROCKHOPPER_CHANGELOG="${ROCKHOPPER_CHANGELOG:-}"
ROCKHOPPER_ARCH="${ROCKHOPPER_ARCH:-noarch}"

usage() {
    printf "Usage: %s [<OPTION>]\n" "$0"
    printf "\n"
    printf -- "--quiet -q\tReduce logging\n"
    printf -- "--debug -d\tIncrease logging\n"
    printf -- "--help -h\tShow usage menu\n"
    printf -- "--version -V\tShow version banner\n"
}

banner() {
    echo "$0 0.0.3"
}

while [ "$#" -ge 1 ]; do
    case "$1" in
    '--quiet' | 'q')
        shift
        ROCKHOPPER_LOG_LEVEL='quiet'
        ;;
    '--debug' | '-d')
        shift
        ROCKHOPPER_LOG_LEVEL='debug'
        ;;
    '--help' | '-h')
        usage
        exit
        ;;
    '--version' | '-V')
        banner
        exit
        ;;
    *)
        usage
        exit 1
        ;;
    esac
done

if [ "$ROCKHOPPER_LOG_LEVEL" = 'debug' ]; then
    env | grep '^ROCKHOPPER_' | sort
    set -x
fi

validate() {
    REQUIRED_ENV_VARS=(
        ROCKHOPPER_NAME
        ROCKHOPPER_VERSION
        ROCKHOPPER_REV
        ROCKHOPPER_SUMMARY
        ROCKHOPPER_DESCRIPTION
        ROCKHOPPER_LICENSE
        ROCKHOPPER_MOUNT
        ROCKHOPPER_DATA_DIR
        ROCKHOPPER_ARTIFACT_DIR
        ROCKHOPPER_RPM_BUILD_DIR
        ROCKHOPPER_CHANGELOG
        ROCKHOPPER_ARCH
    )

    for REQUIRED_ENV_VAR in "${REQUIRED_ENV_VARS[@]}"; do
        eval "REQUIRED_ENV_VAL=\$$REQUIRED_ENV_VAR"

        if [ -z "$REQUIRED_ENV_VAL" ]; then
            echo "error: ${ROCKHOPPER_IMAGE}: blank/missing env var: ${REQUIRED_ENV_VAR}"
            exit 1
        fi
    done
}

clean() {
    rm -rf "$ROCKHOPPER_RPM_BUILD_DIR"
}

validate
clean

LIC=""

if [ -n "$ROCKHOPPER_COPYRIGHT" ]; then
    LIC="$ROCKHOPPER_COPYRIGHT"
fi

LIC="$LIC
$ROCKHOPPER_LICENSE"
printf "$LIC\n" >/tmp/LICENSE

BANNER="${ROCKHOPPER_NAME}-${ROCKHOPPER_VERSION}"
mkdir -p "$ROCKHOPPER_RPM_BUILD_DIR/RHEL"
mkdir -p "$ROCKHOPPER_RPM_BUILD_DIR/$BANNER/data/usr/share/licenses/$ROCKHOPPER_NAME"
cp /tmp/LICENSE "$ROCKHOPPER_RPM_BUILD_DIR/$BANNER/data/usr/share/licenses/$ROCKHOPPER_NAME/LICENSE"
cp -r "$ROCKHOPPER_DATA_DIR"/* "$ROCKHOPPER_RPM_BUILD_DIR/$BANNER/data"

cd "$ROCKHOPPER_RPM_BUILD_DIR"

tar czf "$BANNER.tar.gz" "$BANNER"

mkdir -p "$ROCKHOPPER_RPM_BUILD_DIR/SOURCES"
mv "$ROCKHOPPER_RPM_BUILD_DIR/$BANNER.tar.gz" "$ROCKHOPPER_RPM_BUILD_DIR/SOURCES"
rm -rf "${ROCKHOPPER_RPM_BUILD_DIR:?}/${BANNER:?}"

SPEC="Name: $ROCKHOPPER_NAME
Version: $ROCKHOPPER_VERSION
Release: $ROCKHOPPER_REV%%{?dist}
Summary: $ROCKHOPPER_SUMMARY"

if [ -n "$ROCKHOPPER_URL" ]; then
    SPEC="$SPEC
URL: $ROCKHOPPER_URL"
fi

SPEC="$SPEC
BuildArch: $ROCKHOPPER_ARCH
License: $ROCKHOPPER_LICENSE"

if [ -n "$ROCKHOPPER_DEPENDENCIES" ]; then
    SPEC="$SPEC\nRequires: $ROCKHOPPER_DEPENDENCIES"
fi

SPEC="$SPEC
Source0: $BANNER.tar.gz

%%description
$ROCKHOPPER_DESCRIPTION

%%prep
%%setup -q

%%build
# All assets prebuilt

%%install
mkdir -p \"%%{buildroot}/usr/share/licenses/$ROCKHOPPER_NAME\"
cp /tmp/LICENSE \"%%{buildroot}/usr/share/licenses/$ROCKHOPPER_NAME/LICENSE\"
"

cd "$ROCKHOPPER_DATA_DIR"

for f in $(find . -print); do
    if [ "$f" = './' ]; then
        continue
    fi

    f="${f#./}"

    if [ -d "$f" ]; then
        SPEC="$SPEC\nmkdir -p \"%%{buildroot}/$f\""
    elif [ -f "$f" ]; then
        SPEC="$SPEC\ncp \"$ROCKHOPPER_DATA_DIR/$f\" \"%%{buildroot}/$f\""
    else
        echo "error: ${ROCKHOPPER_IMAGE}: unsupported file system file type for path: ${ROCKHOPPER_DATA_DIR}/${f}"
        exit 1
    fi
done

SPEC="$SPEC\n%%files
/usr/share/licenses/$ROCKHOPPER_NAME/LICENSE
"

for f in $(find . -type f -print); do
    f="${f#./}"
    SPEC="$SPEC\n/$f"
done

cd "$ROCKHOPPER_MOUNT"

SPEC="$SPEC
%%changelog
$(cat "$ROCKHOPPER_CHANGELOG")"

cd "$ROCKHOPPER_RPM_BUILD_DIR"

mkdir -p "$ROCKHOPPER_RPM_BUILD_DIR/SPECS"
SPEC_PATH="$ROCKHOPPER_RPM_BUILD_DIR/SPECS/$ROCKHOPPER_NAME.spec"
printf "$SPEC\n" >"$SPEC_PATH"

if [ "$ROCKHOPPER_LOG_LEVEL" = 'debug' ]; then
    echo "SPEC:"
    cat "$SPEC_PATH"
fi

mkdir -p "$ROCKHOPPER_ARTIFACT_DIR"

if [ "$ROCKHOPPER_LOG_LEVEL" = 'quiet' ]; then
    rpmbuild -bb "$SPEC_PATH" >/dev/null 2>&1
else
    rpmbuild -bb "$SPEC_PATH"
fi

cp "${ROCKHOPPER_RPM_BUILD_DIR}/RPMS/${ROCKHOPPER_ARCH}/${BANNER}-${ROCKHOPPER_REV}."*".${ROCKHOPPER_ARCH}.rpm" "${ROCKHOPPER_ARTIFACT_DIR}"
clean
