#!/bin/bash
unset IFS
set -euo pipefail

usage() {
    printf "Usage: %s <OPTIONS>\n" "$0"
    printf "\n"
    printf -- "--name <name>\t\t\tPackage name (Required, nonblank).\n"
    printf -- "--version <version>\t\tPackage version (Required, nonblank).\n"
    printf -- "--release <release>\t\tPackage release version (Required, nonblank).\n"
    printf -- "--arch <architecture>\t\tPackage architecture (Required, nonblank).\n"
    printf -- "--maintainer <maintainer>\tPackage maintainer of the form \"<name> <email>\" (Required, RFC822 format).\n"
    printf -- "--summmary <summary>\t\tPackage summary (Required, nonblank).\n"
    printf -- "--description <description>\tPackage description (Required, nonblank).\n"
    printf -- "--copyright <copyright>\tPackage copyright (Optional).\n"
    printf -- "--license <license>\t\tPackage license (Required, nonblank).\n"
    printf -- "--dependencies <dependencies>\tPrerequisite package constraints (Optional).\n"
    printf -- "--changelog-file <path>\tChangelog location (Required, nonblank).\n"
    printf -- "--url <homepage>\t\tPackage homepage (Optional).\n"
    printf -- "--help\t\t\t\tShow usage menu.\n"
}

ROCKHOPPER_DATA_DIR='rockhopper-data'
INTERNAL_DIR='/root/rpmbuild'
ARTIFACT_DIR='/src/.rockhopper/rhel'

clean() {
    rm -rf rpmbuild
    rm -rf "$INTERNAL_DIR"
}

while [ "$#" -ge 1 ]; do
    case "$1" in
    '--name')
        shift
        export NAME="$1"
        shift
        ;;
    '--version')
        shift
        export VERSION="$1"
        shift
        ;;
    '--release')
        shift
        export RELEASE="$1"
        shift
        ;;
    '--arch')
        shift
        export ARCH="$1"
        shift
        ;;
    '--maintainer')
        shift
        export MAINTAINER="$1"
        shift
        ;;
    '--summary')
        shift
        export SUMMARY="$1"
        shift
        ;;
    '--description')
        shift
        export DESCRIPTION="$1"
        shift
        ;;
    '--copyright')
        shift
        export COPYRIGHT="$1"
        shift
        ;;
    '--license')
        shift
        export LICENSE="$1"
        shift
        ;;
    '--dependencies')
        shift
        export DEPENDENCIES="$1"
        shift
        ;;
    '--changelog-file')
        shift
        export CHANGELOG_PATH="$1"
        shift
        ;;
    '--url')
        shift
        export URL="$1"
        shift
        ;;
    *)
        usage
        exit 1
        ;;
    esac
done

validate() {
    if [ "${NAME:-}" = '' ]; then
        echo "error: blank/missing --name <name>"
        usage
        exit 1
    fi

    if [ "${VERSION:-}" = '' ]; then
        echo "error: blank/missing --version <version>"
        usage
        exit 1
    fi

    if [ "${RELEASE:-}" = '' ]; then
        echo "error: blank/missing --release <release>"
        usage
        exit 1
    fi

    if [ "${ARCH:-}" = '' ]; then
        echo "error: blank/missing --arch <architecture>"
        usage
        exit 1
    fi

    if [ "${MAINTAINER:-}" = '' ]; then
        echo "error: blank/missing --maintainer <maintainer>"
        usage
        exit 1
    fi

    if [ "${SUMMARY:-}" = '' ]; then
        echo "error: blank/missing --summary <summary>"
        usage
        exit 1
    fi

    if [ "${DESCRIPTION:-}" = '' ]; then
        echo "error: blank/missing --description <description>"
        usage
        exit 1
    fi

    if [ "${LICENSE:-}" = '' ]; then
        echo "error: blank/missing --license <license>"
        usage
        exit 1
    fi

    if [ "${CHANGELOG_PATH:-}" = '' ]; then
        echo "error: blank/missing --changelog-file <path>"
        usage
        exit 1
    fi
}

validate

cd /src

CHANGELOG="$(cat "$CHANGELOG_PATH")"

clean

mkdir -p "$INTERNAL_DIR/RHEL"

BANNER="${NAME}-${VERSION}"

LIC=""

if [ "${COPYRIGHT:-}" != '' ]; then
    LIC="$COPYRIGHT"
fi

LIC="$LIC
$LICENSE"
printf "$LIC\n" >/tmp/LICENSE
mkdir -p "$INTERNAL_DIR/$BANNER/$ROCKHOPPER_DATA_DIR/usr/share/licenses/$NAME"
cp /tmp/LICENSE "$INTERNAL_DIR/$BANNER/$ROCKHOPPER_DATA_DIR/usr/share/licenses/$NAME/LICENSE"

cp -r "$ROCKHOPPER_DATA_DIR" "$INTERNAL_DIR/$BANNER"
cd "$INTERNAL_DIR"
tar czf "$BANNER.tar.gz" "$BANNER"
cd /src
mkdir -p "$INTERNAL_DIR/SOURCES"
mv "$INTERNAL_DIR/$BANNER.tar.gz" "$INTERNAL_DIR/SOURCES"
rm -rf "${INTERNAL_DIR:?}/${BANNER:?}"

SPEC="Name: $NAME
Version: $VERSION
Release: $RELEASE%%{?dist}
Summary: $SUMMARY"

if [ "${URL:-}" != '' ]; then
    SPEC="$SPEC
URL: $URL"
fi

SPEC="$SPEC
BuildArch: $ARCH
License: $LICENSE"

if [ "${DEPENDENCIES:-}" != '' ]; then
    SPEC="$SPEC\nRequires: $DEPENDENCIES"
fi

SPEC="$SPEC
Source0: $BANNER.tar.gz

%%description
$DESCRIPTION

%%prep
%%setup -q

%%build
# All assets prebuilt

%%install
mkdir -p \"%%{buildroot}/usr/share/licenses/$NAME\"
cp /tmp/LICENSE \"%%{buildroot}/usr/share/licenses/$NAME/LICENSE\"
"

cd "/src/$ROCKHOPPER_DATA_DIR"
for f in $(find . -print); do
    f="${f#./}"

    if [ "$f" = '.' ]; then
        continue
    fi

    if [ -d "$f" ]; then
        SPEC="$SPEC\nmkdir -p \"%%{buildroot}/$f\""
    elif [ -f "$f" ]; then
        SPEC="$SPEC\ncp \"/src/$ROCKHOPPER_DATA_DIR/$f\" \"%%{buildroot}/$f\""
    else
        echo "error: unsupported file system file type for path: $ROCKHOPPER_DATA_DIR/$f"
        exit 1
    fi
done

SPEC="$SPEC\n%%files
/usr/share/licenses/$NAME/LICENSE
"

for f in $(find . -type f -print); do
    f="${f#./}"
    SPEC="$SPEC\n/$f"
done
cd "$INTERNAL_DIR"

SPEC="$SPEC
%%changelog
$CHANGELOG"

mkdir -p "$INTERNAL_DIR/SPECS"
SPEC_PATH="$INTERNAL_DIR/SPECS/$NAME.spec"
printf "$SPEC\n" >"$SPEC_PATH"

rpmlint "$SPEC_PATH"

mkdir -p "$ARTIFACT_DIR"

rpmbuild -bb "$SPEC_PATH"

cp "$INTERNAL_DIR/RPMS/$ARCH/$BANNER-$RELEASE."*".$ARCH.rpm" "$ARTIFACT_DIR"

clean
