#!/bin/bash
unset IFS
set -euo pipefail

usage() {
    printf "Usage: %s <OPTIONS>\n" "$0"
    printf "\n"
    printf -- "--name <name>\t\t\tPackage name (Required, nonblank).\n"
    printf -- "--version <version>\t\tPackage version (Required, nonblank).\n"
    printf -- "--release <release>\t\tPackage release version (Required, nonblank).\n"
    printf -- "--arch <architecture>\t\tPackage architecture (Required, nonblank).\n"
    printf -- "--maintainer <maintainer>\tPackage maintainer of the form \"<name> <email>\" (Required, RFC822 format).\n"
    printf -- "--summary <summary>\t\tPackage summary (Required, nonblank).\n"
    printf -- "--description <description>\tPackage description (Ignored).\n"
    printf -- "--copyright <copyright>\tPackage copyright (Optional).\n"
    printf -- "--license <license>\t\tPackage license (Required, nonblank).\n"
    printf -- "--dependencies <dependencies>\tPrerequisite package constraints (Optional, Ignored).\n"
    printf -- "--changelog-file <path>\tChangelog location (Ignored).\n"
    printf -- "--url <homepage>\t\tPackage homepage (Required, nonblank).\n"
    printf -- "--help\t\t\t\tShow usage menu.\n"
}

INTERNAL_DIR='/tmp/build'
ARTIFACT_DIR='.rockhopper/slack'

clean() {
    rm -rf /tmp/*.t?z
    rm -rf "$INTERNAL_DIR"
}

while [ "$#" -ge 1 ]; do
    case "$1" in
    '--help')
        usage
        exit
        ;;
    '--name')
        shift
        export NAME="$1"
        shift
        ;;
    '--version')
        shift
        export VERSION="$1"
        shift
        ;;
    '--release')
        shift
        export RELEASE="$1"
        shift
        ;;
    '--arch')
        shift
        export ARCH="$1"
        shift
        ;;
    '--maintainer')
        shift
        export MAINTAINER="$1"
        shift
        ;;
    '--summary')
        shift
        export SUMMARY="$1"
        shift
        ;;
    '--description')
        shift
        shift
        ;;
    '--copyright')
        shift
        export COPYRIGHT="$1"
        shift
        ;;
    '--license')
        shift
        export LICENSE="$1"
        shift
        ;;
    '--dependencies')
        shift
        export DEPENDENCIES="$1"
        shift
        ;;
    '--changelog-file')
        shift
        shift
        ;;
    '--url')
        shift
        export URL="$1"
        shift
        ;;
    *)
        usage
        exit 1
        ;;
    esac
done

if [ "${NAME:-}" = '' ]; then
    echo "error: blank/missing --name <name>"
    usage
    exit 1
fi

if [ "${VERSION:-}" = '' ]; then
    echo "error: blank/missing --version <version>"
    usage
    exit 1
fi

if [ "${RELEASE:-}" = '' ]; then
    echo "error: blank/missing --release <release>"
    usage
    exit 1
fi

if [ "${ARCH:-}" = '' ]; then
    echo "error: blank/missing --arch <architecture>"
    usage
    exit 1
fi

if [ "${MAINTAINER:-}" = '' ]; then
    echo "error: blank/missing --maintainer <maintainer>"
    usage
    exit 1
fi

if [ "${SUMMARY:-}" = '' ]; then
    echo "error: blank/missing --summary <summary>"
    usage
    exit 1
fi

if [ "${LICENSE:-}" = '' ]; then
    echo "error: blank/missing --license <license>"
    usage
    exit 1
fi

if [ "${URL:-}" = '' ]; then
    echo "error: blank/missing --url <homepage>"
    usage
    exit 1
fi

cd /src

clean

mkdir -p "$INTERNAL_DIR/install"

SLACK_DESC="#
#      |-----handy-ruler------------------------------------------------------|
$NAME: $NAME $SUMMARY
$NAME:
$NAME: $URL
$NAME:
$NAME:
$NAME:
$NAME:
$NAME:
$NAME:
$NAME:
$NAME:"

printf "$SLACK_DESC\n" >"$INTERNAL_DIR/install/slack-desc"

mkdir -p "$INTERNAL_DIR/usr/doc/${NAME}-${VERSION}"

LIC=""

if [ "${COPYRIGHT:-}" != '' ]; then
    LIC="$COPYRIGHT"
fi

LIC="$LIC
$LICENSE"
printf "$LIC\n" >"$INTERNAL_DIR/usr/doc/${NAME}-${VERSION}/LICENSE"
cp -r data/* "$INTERNAL_DIR"

ARTIFACT="${NAME}-${VERSION}-${RELEASE}-${ARCH}-build.tgz"

cd "$INTERNAL_DIR"
makepkg "../$ARTIFACT"
cd /src

mkdir -p "$ARTIFACT_DIR"
cp "/tmp/$ARTIFACT" "$ARTIFACT_DIR"

clean
