#!/bin/bash
unset IFS
set -euo pipefail

ROCKHOPPER_QUIET="${ROCKHOPPER_QUIET:-0}"
ROCKHOPPER_DEBUG="${ROCKHOPPER_DEBUG:-0}"
ROCKHOPPER_IMAGE="${ROCKHOPPER_IMAGE:-unknown image}"
ROCKHOPPER_NAME="${ROCKHOPPER_NAME:-}"
ROCKHOPPER_VERSION="${ROCKHOPPER_VERSION:-}"
ROCKHOPPER_REV="${ROCKHOPPER_REV:-}"
ROCKHOPPER_MAINTAINER="${ROCKHOPPER_MAINTAINER:-}"
ROCKHOPPER_SUMMARY="${ROCKHOPPER_SUMMARY:-}"
ROCKHOPPER_PRIORITY="${ROCKHOPPER_PRIORITY:-optional}"
ROCKHOPPER_DEPENDENCIES="${ROCKHOPPER_DEPENDENCIES:-}"
ROCKHOPPER_COPYRIGHT="${ROCKHOPPER_COPYRIGHT:-}"
ROCKHOPPER_LICENSE="${ROCKHOPPER_LICENSE:-}"
ROCKHOPPER_MOUNT="${ROCKHOPPER_MOUNT:-/mnt/rockhopper}"
ROCKHOPPER_URL="${ROCKHOPPER_URL:-}"
ROCKHOPPER_DATA_DIR="${ROCKHOPPER_DATA_DIR:-$ROCKHOPPER_MOUNT/rockhopper-data}"
ROCKHOPPER_ARTIFACT_DIR="${ROCKHOPPER_ARTIFACT_DIR:-$ROCKHOPPER_MOUNT/.rockhopper/slack}"
ROCKHOPPER_INSTALLPKG_BUILD_DIR="${ROCKHOPPER_INSTALLPKG_BUILD_DIR:-/tmp/build}"
ROCKHOPPER_INSTALLPKG_EXTENSION="${ROCKHOPPER_INSTALLPKG_EXTENSION:-tgz}"
ROCKHOPPER_ARCH="${ROCKHOPPER_ARCH:-noarch}"

usage() {
    printf "Usage: %s [<OPTION>]\n" "$0"
    printf "\n"
    printf -- "--quiet \q\tReduce logging\n"
    printf -- "--debug -d\tIncrease logging\n"
    printf -- "--help -h\tShow usage menu\n"
    printf -- "--version -V\tShow version banner\n"
}

banner() {
    echo "$0 0.0.3"
}

while [ "$#" -ge 1 ]; do
    case "$1" in
    '--quiet' | 'q')
        shift
        ROCKHOPPER_QUIET='1'
        ;;
    '--debug' | '-d')
        shift
        ROCKHOPPER_DEBUG=1
        ;;
    '--help' | '-h')
        usage
        exit
        ;;
    '--version' | '-V')
        banner
        exit
        ;;
    *)
        usage
        exit 1
        ;;
    esac
done

if [ "$ROCKHOPPER_DEBUG" = 1 ]; then
    ROCKHOPPER_QUIET='0'
    env | grep '^ROCKHOPPER_' | sort
    set -x
fi

validate() {
    REQUIRED_ENV_VARS=(
        ROCKHOPPER_NAME
        ROCKHOPPER_VERSION
        ROCKHOPPER_SUMMARY
        ROCKHOPPER_MOUNT
        ROCKHOPPER_DATA_DIR
        ROCKHOPPER_ARTIFACT_DIR
        ROCKHOPPER_INSTALLPKG_BUILD_DIR
        ROCKHOPPER_ARCH
    )

    for REQUIRED_ENV_VAR in "${REQUIRED_ENV_VARS[@]}"; do
        eval "REQUIRED_ENV_VAL=\$$REQUIRED_ENV_VAR"

        if [ -z "$REQUIRED_ENV_VAL" ]; then
            echo "error: ${ROCKHOPPER_IMAGE} blank/missing env var: ${REQUIRED_ENV_VAR}"
            exit 1
        fi
    done
}

clean() {
    rm -rf /tmp/*.t?z
    rm -rf "$ROCKHOPPER_INSTALLPKG_BUILD_DIR"
}

validate
clean

mkdir -p "$ROCKHOPPER_INSTALLPKG_BUILD_DIR/install"

SLACK_DESC="$ROCKHOPPER_NAME: $ROCKHOPPER_NAME $ROCKHOPPER_SUMMARY
$ROCKHOPPER_NAME:
$ROCKHOPPER_NAME: $ROCKHOPPER_URL
$ROCKHOPPER_NAME:
$ROCKHOPPER_NAME:
$ROCKHOPPER_NAME:
$ROCKHOPPER_NAME:
$ROCKHOPPER_NAME:
$ROCKHOPPER_NAME:
$ROCKHOPPER_NAME:
$ROCKHOPPER_NAME:"

printf "$SLACK_DESC\n" >"$ROCKHOPPER_INSTALLPKG_BUILD_DIR/install/slack-desc"

mkdir -p "$ROCKHOPPER_INSTALLPKG_BUILD_DIR/usr/doc/${ROCKHOPPER_NAME}-${ROCKHOPPER_VERSION}"

if [ -n "$ROCKHOPPER_COPYRIGHT" ] || [ -n "$ROCKHOPPER_LICENSE" ]; then
    LIC=""

    if [ -n "$ROCKHOPPER_COPYRIGHT" ]; then
        LIC="$ROCKHOPPER_COPYRIGHT"
    fi

    if [ -n "$ROCKHOPPER_LICENSE" ]; then
        LIC="$LIC
$ROCKHOPPER_LICENSE"
    fi

    printf "$LIC\n" >"$ROCKHOPPER_INSTALLPKG_BUILD_DIR/usr/doc/${ROCKHOPPER_NAME}-${ROCKHOPPER_VERSION}/LICENSE"
fi

cp -r "$ROCKHOPPER_DATA_DIR/"* "$ROCKHOPPER_INSTALLPKG_BUILD_DIR"

cd "$ROCKHOPPER_INSTALLPKG_BUILD_DIR"

mkdir -p "$ROCKHOPPER_ARTIFACT_DIR"
ARTIFACT="${ROCKHOPPER_ARTIFACT_DIR}/${ROCKHOPPER_NAME}-${ROCKHOPPER_VERSION}"

if [ -n "$ROCKHOPPER_REV" ]; then
    ARTIFACT="${ARTIFACT}-${ROCKHOPPER_REV}"
fi

ARTIFACT="${ARTIFACT}-${ROCKHOPPER_ARCH}-build.${ROCKHOPPER_INSTALLPKG_EXTENSION}"

COMMAND="makepkg -c y ${ARTIFACT}"

if [ "$ROCKHOPPER_QUIET" = '1' ]; then
    $COMMAND >/dev/null
else
    $COMMAND
fi

clean
