#!/bin/bash
unset IFS
set -euo pipefail

ROCKHOPPER_LOG_LEVEL="${ROCKHOPPER_LOG_LEVEL:-info}"
ROCKHOPPER_IMAGE="${ROCKHOPPER_IMAGE:-unknown image}"
ROCKHOPPER_NAME="${ROCKHOPPER_NAME:-}"
ROCKHOPPER_VERSION="${ROCKHOPPER_VERSION:-}"
ROCKHOPPER_REV="${ROCKHOPPER_REV:-}"
ROCKHOPPER_COPYRIGHT="${ROCKHOPPER_COPYRIGHT:-}"
ROCKHOPPER_LICENSE="${ROCKHOPPER_LICENSE:-}"
ROCKHOPPER_MOUNT="${ROCKHOPPER_MOUNT:-/mnt/rockhopper}"
ROCKHOPPER_DATA="${ROCKHOPPER_DATA:-$ROCKHOPPER_MOUNT/rockhopper-data}"
ROCKHOPPER_SPECS="${ROCKHOPPER_SPECS:-${HOME}/rockhopper-specs}"
ROCKHOPPER_ARTIFACT="${ROCKHOPPER_ARTIFACT:-$ROCKHOPPER_MOUNT/.rockhopper/slack}"
ROCKHOPPER_INSTALLPKG_BUILD="${ROCKHOPPER_INSTALLPKG_BUILD:-/tmp/build}"
ROCKHOPPER_INSTALLPKG_EXTENSION="${ROCKHOPPER_INSTALLPKG_EXTENSION:-tgz}"
ROCKHOPPER_ARCH="${ROCKHOPPER_ARCH:-noarch}"

# Forward rockhopper environment variables to Jinja
for K in $(compgen -v | grep '^ROCKHOPPER_'); do
    export "$K"
done

usage() {
    printf "Usage: %s [<OPTION>]\n" "$0"
    printf "\n"
    printf -- "--debug -d\tIncrease logging\n"
    printf -- "--quiet -q\tReduce logging\n"
    printf -- "--help -h\tShow usage menu\n"
    printf -- "--version -V\tShow version banner\n"
}

banner() {
    echo "$0 0.0.7"
}

while [ "$#" -ge 1 ]; do
    case "$1" in
    '--debug' | '-d')
        shift
        ROCKHOPPER_LOG_LEVEL='info'
        ;;
    '--quiet' | 'q')
        shift
        ROCKHOPPER_LOG_LEVEL='quiet'
        ;;
    '--help' | '-h')
        usage
        exit
        ;;
    '--version' | '-V')
        banner
        exit
        ;;
    *)
        usage
        exit 1
        ;;
    esac
done

if [ "$ROCKHOPPER_LOG_LEVEL" = 'debug' ]; then
    env | grep '^ROCKHOPPER_' | sort
    set -x
fi

validate() {
    REQUIRED_ENV_VARS=(
        ROCKHOPPER_NAME
        ROCKHOPPER_VERSION
        ROCKHOPPER_MOUNT
        ROCKHOPPER_DATA
        ROCKHOPPER_SPECS
        ROCKHOPPER_ARTIFACT
        ROCKHOPPER_INSTALLPKG_BUILD
        ROCKHOPPER_ARCH
    )

    for REQUIRED_ENV_VAR in "${REQUIRED_ENV_VARS[@]}"; do
        eval "REQUIRED_ENV_VAL=\$$REQUIRED_ENV_VAR"

        if [ -z "$REQUIRED_ENV_VAL" ]; then
            echo "error: ${ROCKHOPPER_IMAGE} blank/missing env var: ${REQUIRED_ENV_VAR}"
            exit 1
        fi
    done
}

clean() {
    rm -rf /tmp/*.t?z
    rm -rf "$ROCKHOPPER_INSTALLPKG_BUILD"
}

validate
clean

mkdir -p "$ROCKHOPPER_INSTALLPKG_BUILD/install"
SLACK_DESC="$ROCKHOPPER_INSTALLPKG_BUILD/install/slack-desc"
rsubst "$ROCKHOPPER_SPECS/slack-desc.j2" >"$SLACK_DESC"

if [ "$ROCKHOPPER_LOG_LEVEL" = 'debug' ]; then
    echo "slack-desc:"
    cat "$SLACK_DESC"
fi

mkdir -p "$ROCKHOPPER_INSTALLPKG_BUILD/usr/doc/${ROCKHOPPER_NAME}-${ROCKHOPPER_VERSION}"

if [ -n "$ROCKHOPPER_COPYRIGHT" ] || [ -n "$ROCKHOPPER_LICENSE" ]; then
    LIC=''

    if [ -n "$ROCKHOPPER_COPYRIGHT" ]; then
        LIC="$ROCKHOPPER_COPYRIGHT"
    fi

    if [ -n "$ROCKHOPPER_LICENSE" ]; then
        LIC="${LIC}\n$ROCKHOPPER_LICENSE"
    fi

    printf "$LIC\n" >"$ROCKHOPPER_INSTALLPKG_BUILD/usr/doc/${ROCKHOPPER_NAME}-${ROCKHOPPER_VERSION}/LICENSE"
fi

cp -r "$ROCKHOPPER_DATA/"* "$ROCKHOPPER_INSTALLPKG_BUILD"

cd "$ROCKHOPPER_INSTALLPKG_BUILD"

mkdir -p "$ROCKHOPPER_ARTIFACT"
ARTIFACT="${ROCKHOPPER_ARTIFACT}/${ROCKHOPPER_NAME}-${ROCKHOPPER_VERSION}"

if [ -n "$ROCKHOPPER_REV" ]; then
    ARTIFACT="${ARTIFACT}-${ROCKHOPPER_REV}"
fi

ARTIFACT="${ARTIFACT}-${ROCKHOPPER_ARCH}-build.${ROCKHOPPER_INSTALLPKG_EXTENSION}"

makepkg() {
    if [ "$ROCKHOPPER_LOG_LEVEL" = 'quiet' ]; then
        command makepkg "$@" >/dev/null 2>&1
    else
        command makepkg "$@"
    fi
}

makepkg -c y "$ARTIFACT"

clean
