#!/bin/bash
unset IFS
set -euo pipefail

ROCKHOPPER_LOG_LEVEL="${ROCKHOPPER_LOG_LEVEL:-info}"
ROCKHOPPER_IMAGE="${ROCKHOPPER_IMAGE:-unknown image}"
ROCKHOPPER_NAME="${ROCKHOPPER_NAME:-}"
ROCKHOPPER_VERSION="${ROCKHOPPER_VERSION:-}"
ROCKHOPPER_REV="${ROCKHOPPER_REV:-}"
ROCKHOPPER_COPYRIGHT="${ROCKHOPPER_COPYRIGHT:-}"
ROCKHOPPER_LICENSE="${ROCKHOPPER_LICENSE:-}"
ROCKHOPPER_MOUNT="${ROCKHOPPER_MOUNT:-/mnt/rockhopper}"
ROCKHOPPER_DATA="${ROCKHOPPER_DATA:-$ROCKHOPPER_MOUNT/rockhopper-data}"
ROCKHOPPER_SPECS="${ROCKHOPPER_SPECS:-${HOME}/rockhopper-specs}"
ROCKHOPPER_ARTIFACT="${ROCKHOPPER_ARTIFACT:-$ROCKHOPPER_MOUNT/.rockhopper/arch}"
ROCKHOPPER_PACMAN_BUILD="${ROCKHOPPER_PACMAN_BUILD:-/tmp/archlinux}"
ROCKHOPPER_ARCH="${ROCKHOPPER_ARCH:-any}"

# Forward rockhopper environment variables to Jinja
for K in $(compgen -v | grep '^ROCKHOPPER_'); do
    export "$K"
done

usage() {
    printf "Usage: %s [<OPTION>]\n" "$0"
    printf "\n"
    printf -- "--debug -d\tIncrease logging\n"
    printf -- "--quiet -q\tReduce logging\n"
    printf -- "--help -h\tShow usage menu\n"
    printf -- "--version -V\tShow version banner\n"
}

banner() {
    echo "$0 0.0.7"
}

while [ "$#" -ge 1 ]; do
    case "$1" in
    '--debug' | '-d')
        shift
        ROCKHOPPER_LOG_LEVEL='debug'
        ;;
    '--quiet' | 'q')
        shift
        ROCKHOPPER_LOG_LEVEL='quiet'
        ;;
    '--help' | '-h')
        usage
        exit
        ;;
    '--version' | '-V')
        banner
        exit
        ;;
    *)
        usage
        exit 1
        ;;
    esac
done

if [ "$ROCKHOPPER_LOG_LEVEL" = 'debug' ]; then
    env | grep '^ROCKHOPPER_' | sort
    set -x
fi

validate() {
    REQUIRED_ENV_VARS=(
        ROCKHOPPER_NAME
        ROCKHOPPER_VERSION
        ROCKHOPPER_REV
        ROCKHOPPER_LICENSE
        ROCKHOPPER_MOUNT
        ROCKHOPPER_DATA
        ROCKHOPPER_SPECS
        ROCKHOPPER_ARTIFACT
        ROCKHOPPER_PACMAN_BUILD
        ROCKHOPPER_ARCH
    )

    for REQUIRED_ENV_VAR in "${REQUIRED_ENV_VARS[@]}"; do
        eval "REQUIRED_ENV_VAL=\$$REQUIRED_ENV_VAR"

        if [ -z "$REQUIRED_ENV_VAL" ]; then
            echo "error: ${ROCKHOPPER_IMAGE} blank/missing env var: ${REQUIRED_ENV_VAR}"
            exit 1
        fi
    done
}

clean() {
    rm -rf "$ROCKHOPPER_PACMAN_BUILD"
}

validate
clean

cd "$ROCKHOPPER_DATA"

PACMAN_SOURCES=''

for f in $(find . -type f -print); do
    f="${f#./}"
    b="$(basename "$f")"

    PACMAN_SOURCES="$PACMAN_SOURCES\"$b\" "
done

export PACMAN_SOURCES

PACMAN_PACKAGE=''

for f in $(find . -print); do
    if [ "$f" = './' ]; then
        continue
    fi

    f="${f#./}"

    if [ -d "$f" ]; then
        PACMAN_PACKAGE="${PACMAN_PACKAGE}install -d \"\${pkgdir}/$f\"; "
    elif [ -f "$f" ]; then
        b="$(basename "$f")"
        PACMAN_PACKAGE="${PACMAN_PACKAGE}install \"\${srcdir}/$b\" \"\${pkgdir}/$f\"; "
    else
        echo "error: ${ROCKHOPPER_IMAGE}: unsupported file system file type for path: ${f}"
    fi
done

export PACMAN_PACKAGE
PKGBUILD="$ROCKHOPPER_PACMAN_BUILD/PKGBUILD"

mkdir -p "$ROCKHOPPER_PACMAN_BUILD/src"
rsubst "$ROCKHOPPER_SPECS/PKGBUILD.j2" >"$PKGBUILD"

if [ "$ROCKHOPPER_LOG_LEVEL" = 'debug' ]; then
    echo "PKGBUILD:"
    cat "$PKGBUILD"
fi

if [ -n "$ROCKHOPPER_COPYRIGHT" ] || [ -n "$ROCKHOPPER_LICENSE" ]; then
    LIC=''

    if [ -n "$ROCKHOPPER_COPYRIGHT" ]; then
        LIC="$ROCKHOPPER_COPYRIGHT"
    fi

    if [ -n "$ROCKHOPPER_LICENSE" ]; then
        LIC="${LIC}\n$ROCKHOPPER_LICENSE"
    fi

    printf "$LIC\n" >"$ROCKHOPPER_PACMAN_BUILD/src/LICENSE"
fi

find "$ROCKHOPPER_DATA" -type f -exec cp "{}" "$ROCKHOPPER_PACMAN_BUILD" \;

cd "$ROCKHOPPER_PACMAN_BUILD"

makepkg() {
    HAS_GENINTEG=''

    for ARG in "$@"; do
        if [ "$ARG" = '-g' ] || [ "$ARG" = '--geninteg' ]; then
            HAS_GENINTEG='1'
            break
        fi
    done

    if [ "$ROCKHOPPER_LOG_LEVEL" = 'quiet' ]; then
        if [ -n "$HAS_GENINTEG" ]; then
            command makepkg "$@" 2>/dev/null
        else
            command makepkg "$@" >/dev/null 2>&1
        fi
    else
        command makepkg "$@"
    fi
}

# Update sha256sums
makepkg -g >>PKGBUILD

makepkg

mkdir -p "$ROCKHOPPER_ARTIFACT"

cp \
    "${ROCKHOPPER_PACMAN_BUILD}/$ROCKHOPPER_NAME-$ROCKHOPPER_VERSION-$ROCKHOPPER_REV-$ROCKHOPPER_ARCH.pkg.tar.zst" \
    "$ROCKHOPPER_ARTIFACT"

clean
