#!/bin/bash
unset IFS
set -euo pipefail

usage() {
    printf "Usage: %s <OPTIONS>\n" "$0"
    printf "\n"
    printf -- "--name <name>\t\t\tPackage name (Required, nonblank).\n"
    printf -- "--version <version>\t\tPackage version (Required, nonblank).\n"
    printf -- "--release <release>\t\tPackage release version (Required, nonblank).\n"
    printf -- "--arch <architecture>\t\tPackage architecture (Required, nonblank).\n"
    printf -- "--maintainer <maintainer>\tPackage maintainer of the form \"<name> <email>\" (Required, RFC822 format).\n"
    printf -- "--summary <summary>\t\tPackage summary (Ignored).\n"
    printf -- "--description <description>\tPackage description (Required, nonblank).\n"
    printf -- "--copyright <copyright>\t\tPackage copyright (Optional).\n"
    printf -- "--license <license>\t\tPackage license (Required, nonblank).\n"
    printf -- "--dependencies <dependencies>\tPrerequisite package constraints (Optional).\n"
    printf -- "--changelog-file <path>\t\tChangelog location (Ignored).\n"
    printf -- "--url <homepage>\t\tPackage homepage (Required, nonblank).\n"
    printf -- "--help\t\t\t\tShow usage menu.\n"
    printf -- "-V\t\t\t\tShow version banner.\n"
}

banner() {
    echo 'rockhopper 0.0.1'
}

ROCKHOPPER_MOUNT='/mnt/rockhopper'
ROCKHOPPER_DATA_DIR="$ROCKHOPPER_MOUNT/rockhopper-data"
ROCKHOPPER_ARTIFACT_DIR="$ROCKHOPPER_MOUNT/.rockhopper/arch"
PACMAN_BUILD_DIR='/tmp/archlinux'

clean() {
    rm -rf "$PACMAN_BUILD_DIR"
}

while [ "$#" -ge 1 ]; do
    case "$1" in
    '--help')
        usage
        exit
        ;;
    '-V')
        banner
        exit
        ;;
    '--name')
        shift
        export NAME="$1"
        shift
        ;;
    '--version')
        shift
        export VERSION="$1"
        shift
        ;;
    '--release')
        shift
        export RELEASE="$1"
        shift
        ;;
    '--arch')
        shift
        export ARCH="$1"
        shift
        ;;
    '--maintainer')
        shift
        export MAINTAINER="$1"
        shift
        ;;
    '--summary')
        shift
        shift
        ;;
    '--description')
        shift
        export DESCRIPTION="$1"
        shift
        ;;
    '--copyright')
        shift
        export COPYRIGHT="$1"
        shift
        ;;
    '--license')
        shift
        export LICENSE="$1"
        shift
        ;;
    '--dependencies')
        shift
        export DEPENDENCIES="$1"
        shift
        ;;
    '--changelog-file')
        shift
        shift
        ;;
    '--url')
        shift
        export URL="$1"
        shift
        ;;
    *)
        usage
        exit 1
        ;;
    esac
done

validate() {
    if [ -z "${NAME:-}" ]; then
        echo "error: blank/missing --name <name>"
        usage
        exit 1
    fi

    if [ -z "${VERSION:-}" ]; then
        echo "error: blank/missing --version <version>"
        usage
        exit 1
    fi

    if [ -z "${RELEASE:-}" ]; then
        echo "error: blank/missing --release <release>"
        usage
        exit 1
    fi

    if [ -z "${ARCH:-}" ]; then
        echo "error: blank/missing --arch <architecture>"
        usage
        exit 1
    fi

    if [ -z "${MAINTAINER:-}" ]; then
        echo "error: blank/missing --maintainer <maintainer>"
        usage
        exit 1
    fi

    if [ -z "${DESCRIPTION:-}" ]; then
        echo "error: blank/missing --description <description>"
        usage
        exit 1
    fi

    if [ -z "${LICENSE:-}" ]; then
        echo "error: blank/missing --license <license>"
        usage
        exit 1
    fi

    if [ -z "${URL:-}" ]; then
        echo "error: blank/missing --url <homepage>"
        usage
        exit 1
    fi
}

validate
clean

PKGBUILD="# Maintainer: $MAINTAINER
pkgname=$NAME
pkgver=$VERSION
pkgrel=$RELEASE
pkgdesc=\"$DESCRIPTION\"
arch=($ARCH)
url=\"$URL\"
license=('$LICENSE')
depends=(${DEPENDENCIES:-})
source=("

cd "$ROCKHOPPER_DATA_DIR"

for f in $(find . -type f -print); do
    f="${f#./}"
    b="$(basename "$f")"

    PKGBUILD="$PKGBUILD\n    \"$b\""
done

PKGBUILD="$PKGBUILD
)
sha256sums=('...')

package() {
    install -d \"\${pkgdir}/usr/share/licenses/$NAME\"
    install \"\${srcdir}/LICENSE\" \"\${pkgdir}/usr/share/licenses/$NAME/LICENSE\"
"

for f in $(find . -print); do
    if [ "$f" = './' ]; then
        continue
    fi

    f="${f#./}"

    if [ -d "$f" ]; then
        PKGBUILD="$PKGBUILD\n    install -d \"\${pkgdir}/$f\""
    elif [ -f "$f" ]; then
        b="$(basename "$f")"
        PKGBUILD="$PKGBUILD\n    install \"\${srcdir}/$b\" \"\${pkgdir}/$f\""
    else
        echo "error: unsupported file system file type for path: $f"
    fi
done

PKGBUILD="$PKGBUILD\n}"

mkdir -p "$PACMAN_BUILD_DIR"
printf "$PKGBUILD\n" >"$PACMAN_BUILD_DIR/PKGBUILD"

LIC=""

if [ -n "${COPYRIGHT:-}" ]; then
    LIC="$COPYRIGHT"
fi

LIC="$LIC
$LICENSE"
mkdir -p "$PACMAN_BUILD_DIR/src"
printf "$LIC\n" >"$PACMAN_BUILD_DIR/src/LICENSE"

find "$ROCKHOPPER_DATA_DIR" -type f -exec cp "{}" "$PACMAN_BUILD_DIR" \;

cd "$PACMAN_BUILD_DIR"

# Update sha256sums
makepkg -g >>PKGBUILD

makepkg
mkdir -p "$ROCKHOPPER_ARTIFACT_DIR"
cp "${PACMAN_BUILD_DIR}/${NAME}-${VERSION}-${RELEASE}-${ARCH}.pkg.tar.zst" "$ROCKHOPPER_ARTIFACT_DIR"
clean
