#!/bin/bash
unset IFS
set -euo pipefail

ROCKHOPPER_LOG_LEVEL="${ROCKHOPPER_LOG_LEVEL:-}"
ROCKHOPPER_IMAGE="${ROCKHOPPER_IMAGE:-unknown image}"
ROCKHOPPER_NAME="${ROCKHOPPER_NAME:-}"
ROCKHOPPER_VERSION="${ROCKHOPPER_VERSION:-}"
ROCKHOPPER_REV="${ROCKHOPPER_REV:-}"
ROCKHOPPER_MAINTAINER="${ROCKHOPPER_MAINTAINER:-}"
ROCKHOPPER_DESCRIPTION="${ROCKHOPPER_DESCRIPTION:-}"
ROCKHOPPER_DEPENDENCIES="${ROCKHOPPER_DEPENDENCIES:-}"
ROCKHOPPER_COPYRIGHT="${ROCKHOPPER_COPYRIGHT:-}"
ROCKHOPPER_LICENSE="${ROCKHOPPER_LICENSE:-}"
ROCKHOPPER_MOUNT="${ROCKHOPPER_MOUNT:-/mnt/rockhopper}"
ROCKHOPPER_URL="${ROCKHOPPER_URL:-}"
ROCKHOPPER_DATA_DIR="${ROCKHOPPER_DATA_DIR:-$ROCKHOPPER_MOUNT/rockhopper-data}"
ROCKHOPPER_ARTIFACT_DIR="${ROCKHOPPER_ARTIFACT_DIR:-$ROCKHOPPER_MOUNT/.rockhopper/arch}"
ROCKHOPPER_PACMAN_BUILD_DIR="${ROCKHOPPER_PACMAN_BUILD_DIR:-/tmp/archlinux}"
ROCKHOPPER_ARCH="${ROCKHOPPER_ARCH:-any}"

usage() {
    printf "Usage: %s [<OPTION>]\n" "$0"
    printf "\n"
    printf -- "--quiet -q\tReduce logging\n"
    printf -- "--debug -d\tIncrease logging\n"
    printf -- "--help -h\tShow usage menu\n"
    printf -- "--version -V\tShow version banner\n"
}

banner() {
    echo "$0 0.0.3"
}

while [ "$#" -ge 1 ]; do
    case "$1" in
    '--quiet' | 'q')
        shift
        ROCKHOPPER_LOG_LEVEL='quiet'
        ;;
    '--debug' | '-d')
        shift
        ROCKHOPPER_LOG_LEVEL='debug'
        ;;
    '--help' | '-h')
        usage
        exit
        ;;
    '--version' | '-V')
        banner
        exit
        ;;
    *)
        usage
        exit 1
        ;;
    esac
done

if [ "$ROCKHOPPER_LOG_LEVEL" = 'debug' ]; then
    env | grep '^ROCKHOPPER_' | sort
    set -x
fi

validate() {
    REQUIRED_ENV_VARS=(
        ROCKHOPPER_NAME
        ROCKHOPPER_VERSION
        ROCKHOPPER_REV
        ROCKHOPPER_DESCRIPTION
        ROCKHOPPER_LICENSE
        ROCKHOPPER_MOUNT
        ROCKHOPPER_URL
        ROCKHOPPER_DATA_DIR
        ROCKHOPPER_ARTIFACT_DIR
        ROCKHOPPER_PACMAN_BUILD_DIR
        ROCKHOPPER_ARCH
    )

    for REQUIRED_ENV_VAR in "${REQUIRED_ENV_VARS[@]}"; do
        eval "REQUIRED_ENV_VAL=\$$REQUIRED_ENV_VAR"

        if [ -z "$REQUIRED_ENV_VAL" ]; then
            echo "error: ${ROCKHOPPER_IMAGE} blank/missing env var: ${REQUIRED_ENV_VAR}"
            exit 1
        fi
    done
}

clean() {
    rm -rf "$ROCKHOPPER_PACMAN_BUILD_DIR"
}

validate
clean

PKGBUILD="# Maintainer: $ROCKHOPPER_MAINTAINER
pkgname=$ROCKHOPPER_NAME
pkgver=$ROCKHOPPER_VERSION
pkgrel=$ROCKHOPPER_REV
pkgdesc=\"$ROCKHOPPER_DESCRIPTION\"
arch=($ROCKHOPPER_ARCH)
url=\"$ROCKHOPPER_URL\""

if [ -n "$ROCKHOPPER_LICENSE" ]; then
    PKGBUILD="$PKGBUILD
license=('$ROCKHOPPER_LICENSE')"
fi

PKGBUILD="$PKGBUILD
depends=($ROCKHOPPER_DEPENDENCIES)
source=("

cd "$ROCKHOPPER_DATA_DIR"

for f in $(find . -type f -print); do
    f="${f#./}"
    b="$(basename "$f")"

    PKGBUILD="$PKGBUILD\n    \"$b\""
done

PKGBUILD="$PKGBUILD
)
sha256sums=('...')

package() {"

if [ -n "$ROCKHOPPER_COPYRIGHT" ] || [ -n "$ROCKHOPPER_LICENSE" ]; then
    PKGBUILD="$PKGBUILD
    install -d \"\${pkgdir}/usr/share/licenses/$ROCKHOPPER_NAME\"
    install \"\${srcdir}/LICENSE\" \"\${pkgdir}/usr/share/licenses/$ROCKHOPPER_NAME/LICENSE\"
"
fi

for f in $(find . -print); do
    if [ "$f" = './' ]; then
        continue
    fi

    f="${f#./}"

    if [ -d "$f" ]; then
        PKGBUILD="$PKGBUILD\n    install -d \"\${pkgdir}/$f\""
    elif [ -f "$f" ]; then
        b="$(basename "$f")"
        PKGBUILD="$PKGBUILD\n    install \"\${srcdir}/$b\" \"\${pkgdir}/$f\""
    else
        echo "error: ${ROCKHOPPER_IMAGE}: unsupported file system file type for path: ${f}"
    fi
done

PKGBUILD="$PKGBUILD\n}"

mkdir -p "$ROCKHOPPER_PACMAN_BUILD_DIR/src"
printf "$PKGBUILD\n" >"$ROCKHOPPER_PACMAN_BUILD_DIR/PKGBUILD"

if [ "$ROCKHOPPER_LOG_LEVEL" = 'debug' ]; then
    echo "PKGBUILD:"
    cat "$ROCKHOPPER_PACMAN_BUILD_DIR/PKGBUILD"
fi

if [ -n "$ROCKHOPPER_COPYRIGHT" ] || [ -n "$ROCKHOPPER_LICENSE" ]; then
    LIC=""

    if [ -n "$ROCKHOPPER_COPYRIGHT" ]; then
        LIC="$ROCKHOPPER_COPYRIGHT"
    fi

    if [ -n "$ROCKHOPPER_LICENSE" ]; then
        LIC="$LIC
$ROCKHOPPER_LICENSE"
    fi

    printf "$LIC\n" >"$ROCKHOPPER_PACMAN_BUILD_DIR/src/LICENSE"
fi

find "$ROCKHOPPER_DATA_DIR" -type f -exec cp "{}" "$ROCKHOPPER_PACMAN_BUILD_DIR" \;

cd "$ROCKHOPPER_PACMAN_BUILD_DIR"

#
# Update sha256sums
#

if [ "$ROCKHOPPER_LOG_LEVEL" = 'quiet' ]; then
    makepkg -g >>PKGBUILD 2>/dev/null
else
    makepkg -g >>PKGBUILD
fi

if [ "$ROCKHOPPER_LOG_LEVEL" = 'quiet' ]; then
    makepkg >/dev/null 2>&1
else
    makepkg
fi

mkdir -p "$ROCKHOPPER_ARTIFACT_DIR"
cp "${ROCKHOPPER_PACMAN_BUILD_DIR}/$ROCKHOPPER_NAME-$ROCKHOPPER_VERSION-$ROCKHOPPER_REV-$ROCKHOPPER_ARCH.pkg.tar.zst" "$ROCKHOPPER_ARTIFACT_DIR"
clean
