#!/bin/bash
unset IFS
set -eufo pipefail

ROCKHOPPER_LOG_LEVEL='quiet'
# ROCKHOPPER_LOG_LEVEL='debug'
ROCKHOPPER_NAME='hello'
ROCKHOPPER_VERSION='1.0.0'
ROCKHOPPER_REV='1'
ROCKHOPPER_MAINTAINER='Bob Loblaw <bob@bananastand.test>'
ROCKHOPPER_SUMMARY='greeter'
ROCKHOPPER_DESCRIPTION='hello world welcomes new developers'
ROCKHOPPER_COPYRIGHT='Copyright (C) 2026 Bob'
ROCKHOPPER_LICENSE='0BSD'
ROCKHOPPER_CHANGELOG='CHANGELOG.txt'
ROCKHOPPER_URL='https://bobslawblog.test/'

for K in $(compgen -v | grep '^ROCKHOPPER_'); do
    export "$K"
done

PLATFORMS=(
    n4jm4/rockhopper:alpine#noarch
    n4jm4/rockhopper:arch#any
    n4jm4/rockhopper:debian#all
    n4jm4/rockhopper:fedora#noarch
    n4jm4/rockhopper:slack#noarch
)

for PLATFORM in "${PLATFORMS[@]}"; do
    IMAGE="${PLATFORM%%#*}"
    ARCH="${PLATFORM#*#}"

    echo "building $PLATFORM"
    env ROCKHOPPER_IMAGE="$IMAGE" ROCKHOPPER_ARCH="$ARCH" rockhopper
done
