#!/bin/bash
unset IFS
set -euo pipefail

ROCKHOPPER_LOG_LEVEL="${ROCKHOPPER_LOG_LEVEL:-info}"
ROCKHOPPER_IMAGE="${ROCKHOPPER_IMAGE:-unknown image}"
ROCKHOPPER_NAME="${ROCKHOPPER_NAME:-}"
ROCKHOPPER_VERSION="${ROCKHOPPER_VERSION:-}"
ROCKHOPPER_REV="${ROCKHOPPER_REV:-}"
ROCKHOPPER_COPYRIGHT="${ROCKHOPPER_COPYRIGHT:-}"
ROCKHOPPER_LICENSE="${ROCKHOPPER_LICENSE:-}"
ROCKHOPPER_MOUNT="${ROCKHOPPER_MOUNT:-/mnt/rockhopper}"
ROCKHOPPER_DATA="${ROCKHOPPER_DATA:-"$ROCKHOPPER_MOUNT/rockhopper-data"}"
ROCKHOPPER_SPECS="${ROCKHOPPER_SPECS:-"$HOME/rockhopper-specs"}"
ROCKHOPPER_ARTIFACT="${ROCKHOPPER_ARTIFACT:-"$ROCKHOPPER_MOUNT/.rockhopper/void-linux"}"
ROCKHOPPER_XBPS_BUILD="${ROCKHOPPER_XBPS_BUILD:-/tmp/void-linux-musl}"
ROCKHOPPER_ARCH="${ROCKHOPPER_ARCH:-*}"

# Forward rockhopper environment variables to Jinja
for K in $(compgen -v | grep '^ROCKHOPPER_'); do
    export "$K"
done

usage() {
    printf "Usage: %s [<OPTION>]\n" "$0"
    printf "\n"
    printf -- "--debug -d\tIncrease logging\n"
    printf -- "--quiet -q\tReduce logging\n"
    printf -- "--help -h\tShow usage menu\n"
    printf -- "--version -V\tShow version banner\n"
}

banner() {
    echo "$0 0.0.7"
}

while [ "$#" -ge 1 ]; do
    case "$1" in
    '--debug' | '-d')
        shift
        ROCKHOPPER_LOG_LEVEL='debug'
        ;;
    '--quiet' | 'q')
        shift
        ROCKHOPPER_LOG_LEVEL='quiet'
        ;;
    '--help' | '-h')
        usage
        exit
        ;;
    '--version' | '-V')
        banner
        exit
        ;;
    *)
        usage
        exit 1
        ;;
    esac
done

if [ "$ROCKHOPPER_LOG_LEVEL" = 'debug' ]; then
    env | grep '^ROCKHOPPER_' | sort
    set -x
fi

validate() {
    REQUIRED_ENV_VARS=(
        ROCKHOPPER_NAME
        ROCKHOPPER_VERSION
        ROCKHOPPER_REV
        ROCKHOPPER_LICENSE
        ROCKHOPPER_MOUNT
        ROCKHOPPER_DATA
        ROCKHOPPER_SPECS
        ROCKHOPPER_ARTIFACT
        ROCKHOPPER_XBPS_BUILD
        ROCKHOPPER_ARCH
    )

    for REQUIRED_ENV_VAR in "${REQUIRED_ENV_VARS[@]}"; do
        eval "REQUIRED_ENV_VAL=\$$REQUIRED_ENV_VAR"

        if [ -z "$REQUIRED_ENV_VAL" ]; then
            echo "error: ${ROCKHOPPER_IMAGE} blank/missing env var: ${REQUIRED_ENV_VAR}"
            exit 1
        fi
    done
}

clean() {
    rm -rf "$ROCKHOPPER_XBPS_BUILD"
}

validate
clean

git-clone() {
    if [ "$ROCKHOPPER_LOG_LEVEL" = 'quiet' ]; then
        command git clone -q "$@"
    else
        command git clone "$@"
    fi
}

git-clone --depth 1 https://github.com/void-linux/void-packages.git "$ROCKHOPPER_XBPS_BUILD"
XBPS_SRC="$ROCKHOPPER_XBPS_BUILD/srcpkgs/$ROCKHOPPER_NAME"
mkdir -p "$XBPS_SRC"

LIC=''

if [ -n "$ROCKHOPPER_COPYRIGHT" ]; then
    LIC="Copyright: $ROCKHOPPER_COPYRIGHT"
fi

LIC="${LIC}\nLicense: $ROCKHOPPER_LICENSE"
FILES="$XBPS_SRC/files"
LICENSES="$FILES/licenses"
mkdir -p "$LICENSES"
printf "$LIC\n" >"$LICENSES/LICENSE"
DATA="$FILES/data"
mkdir -p "$DATA"
cp -r "$ROCKHOPPER_DATA/"* "$DATA"

cd "$FILES"

XBPS_PRE_INSTALL=''

for f in $(find . -print); do
    f="${f#./}"

    if [ "$f" = '.' ]; then
        continue
    fi

    if [ -d "$f" ]; then
        XBPS_PRE_INSTALL="${XBPS_PRE_INSTALL}mkdir -p \"$f\"; "
    elif [ -f "$f" ]; then
        XBPS_PRE_INSTALL="${XBPS_PRE_INSTALL}cp \"\$FILESDIR/$f\" \"$f\"; "
    else
        echo "error: ${ROCKHOPPER_IMAGE}: unsupported file system file type for path: ${f}"
    fi
done

export XBPS_PRE_INSTALL

cd "$DATA"

XBPS_PACKAGE=''

for f in $(find . -print); do
    f="${f#./}"

    if [ "$f" = '.' ]; then
        continue
    fi

    if [ -d "$f" ]; then
        XBPS_PACKAGE="${XBPS_PACKAGE}vmkdir \"$f\"; "
    elif [ -f "$f" ]; then
        XBPS_PACKAGE="${XBPS_PACKAGE}vcopy \"data/$f\" \"$f\"; "
    else
        echo "error: ${ROCKHOPPER_IMAGE}: unsupported file system file type for path: ${f}"
    fi
done

export XBPS_PACKAGE

TEMPLATE="$XBPS_SRC/template"
rsubst "$ROCKHOPPER_SPECS/template.j2" >"$TEMPLATE"

if [ "$ROCKHOPPER_LOG_LEVEL" = 'debug' ]; then
    echo "template:"
    cat "$TEMPLATE"
fi

xbps-src() {
    if [ "$ROCKHOPPER_LOG_LEVEL" = 'quiet' ]; then
        ./xbps-src "$@" >/dev/null 2>&1
    else
        ./xbps-src "$@"
    fi
}

cd "$ROCKHOPPER_XBPS_BUILD"

xbps-src pkg "$ROCKHOPPER_NAME"
mkdir -p "$ROCKHOPPER_ARTIFACT"
cp "$ROCKHOPPER_XBPS_BUILD/hostdir/binpkgs/"*.xbps "$ROCKHOPPER_ARTIFACT"
clean
